// 004bb18f-ba0c-4cae-b281-4740b6c51221/src/pages/VehicleInfo.tsx
import React, { useState } from 'react';
import { InputField } from '../components/InputField';
import { Dropdown } from '../components/Dropdown';
import { Button } from '../components/Button';
interface VehicleData {
  registration: string;
  brand: string;
  mileage: string;
  model: string; // Ajout du champ modèle
}
interface VehicleInfoProps {
  data: VehicleData;
  updateData: (data: Partial<VehicleData>) => void;
  onNext: () => void;
  onPrevious: () => void;
}
export const VehicleInfo = ({
  data,
  updateData,
  onNext,
  onPrevious
}: VehicleInfoProps) => {
  const [errors, setErrors] = useState({
    registration: '',
    brand: '',
    mileage: '',
    model: '' // Ajout de l'erreur pour le modèle
  });
  const carBrands = ['Audi', 'BMW', 'Citroën', 'Dacia', 'Fiat', 'Ford', 'Honda', 'Hyundai', 'Kia', 'Mercedes', 'Nissan', 'Opel', 'Peugeot', 'Renault', 'Seat', 'Skoda', 'Toyota', 'Volkswagen', 'Volvo'];
  const validate = () => {
    const newErrors = {
      registration: '',
      brand: '',
      mileage: '',
      model: ''
    };
    if (!data.registration.trim()) {
      newErrors.registration = "L'immatriculation est requise";
    }
    if (!data.brand) {
      newErrors.brand = 'La marque est requise';
    }
    if (!data.mileage.trim()) {
      newErrors.mileage = 'Le kilométrage est requis';
    } else if (isNaN(Number(data.mileage))) {
      newErrors.mileage = 'Le kilométrage doit être un nombre';
    }
    // Validation du modèle
    if (!data.model || !data.model.trim()) {
      newErrors.model = 'Le modèle est requis';
    }
    setErrors(newErrors);
    return !Object.values(newErrors).some(error => error);
  };
  const handleNext = () => {
    if (validate()) {
      onNext();
    }
  };
  return <div className="animate-fadeIn">
      <h2 className="text-2xl font-bold text-[#333333] mb-6">
        Informations du véhicule
      </h2>
      <InputField label="Immatriculation" id="registration" value={data.registration} onChange={value => updateData({
      registration: value
    })} placeholder="AB-123-CD" required error={errors.registration} />
      <Dropdown label="Marque" id="brand" value={data.brand} onChange={value => updateData({
      brand: value
    })} options={carBrands} required error={errors.brand} />
      {/* Ajout du champ modèle */}
      <InputField label="Modèle" id="model" value={data.model || ''} onChange={value => updateData({
      model: value
    })} placeholder="Ex: Clio, Golf, 308..." required error={errors.model} />
      <InputField label="Kilométrage" id="mileage" value={data.mileage} onChange={value => updateData({
      mileage: value
    })} placeholder="Entrez le kilométrage" type="number" required error={errors.mileage} />
      <div className="mt-8 flex justify-between">
        <Button onClick={onPrevious} variant="secondary">
          Précédent
        </Button>
        <Button onClick={handleNext}>Suivant</Button>
      </div>
    </div>;
};

// src/app/features/repair-order/vehicle-info/vehicle-info.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { VehicleInfo } from '../../../shared/models/repair-order.model';
import { InputFieldComponent } from '../../../shared/components/input-field/input-field.component';
import { DropdownComponent } from '../../../shared/components/dropdown/dropdown.component';
import { ButtonComponent } from '../../../shared/components/button/button.component';

@Component({
  selector: 'app-vehicle-info',
  standalone: true,
  imports: [
    CommonModule,
    InputFieldComponent,
    DropdownComponent,
    ButtonComponent
  ],
  templateUrl: './vehicle-info.component.html',
  styleUrl: './vehicle-info.component.scss'
})
export class VehicleInfoComponent {
  @Input() data: VehicleInfo = {
    registration: '',
    brand: '',
    mileage: '',
    model: ''
  };
  
  @Output() dataChange = new EventEmitter<VehicleInfo>();
  @Output() nextStep = new EventEmitter<void>();
  @Output() previousStep = new EventEmitter<void>();

  carBrands = [
    'Audi', 'BMW', 'Citroën', 'Dacia', 'Fiat', 'Ford', 
    'Honda', 'Hyundai', 'Kia', 'Mercedes', 'Nissan', 
    'Opel', 'Peugeot', 'Renault', 'Seat', 'Skoda', 
    'Toyota', 'Volkswagen', 'Volvo'
  ];

  errors = {
    registration: '',
    brand: '',
    mileage: '',
    model: ''
  };

  onFieldChange(field: keyof VehicleInfo, value: string): void {
    this.data = { ...this.data, [field]: value };
    this.dataChange.emit(this.data);
    
    if (this.errors[field as keyof typeof this.errors] !== undefined) {
      this.errors[field as keyof typeof this.errors] = '';
    }
  }

  validate(): boolean {
    this.errors = {
      registration: '',
      brand: '',
      mileage: '',
      model: ''
    };

    if (!this.data.registration.trim()) {
      this.errors.registration = "L'immatriculation est requise";
    }

    if (!this.data.brand) {
      this.errors.brand = 'La marque est requise';
    }

    if (!this.data.mileage.trim()) {
      this.errors.mileage = 'Le kilométrage est requis';
    } else if (isNaN(Number(this.data.mileage))) {
      this.errors.mileage = 'Le kilométrage doit être un nombre';
    }

    if (!this.data.model || !this.data.model.trim()) {
      this.errors.model = 'Le modèle est requis';
    }

    return !Object.values(this.errors).some(error => error);
  }

  onNext(): void {
    if (this.validate()) {
      this.nextStep.emit();
    }
  }

  onPrevious(): void {
    this.previousStep.emit();
  }
}
<div class="vehicle-info-container">
  <h2 class="page-title">Informations du véhicule</h2>
  
  <div class="form-container">
    <app-input-field
      label="Immatriculation"
      [value]="data.registration"
      (valueChange)="onFieldChange('registration', $event)"
      placeholder="AB-123-CD"
      [required]="true"
      [error]="errors.registration"
    ></app-input-field>

    <app-dropdown
      label="Marque"
      [value]="data.brand"
      (valueChange)="onFieldChange('brand', $event)"
      [options]="carBrands"
      [required]="true"
      [error]="errors.brand"
      placeholder="Sélectionner une marque"
    ></app-dropdown>

    <app-input-field
      label="Modèle"
      [value]="data.model"
      (valueChange)="onFieldChange('model', $event)"
      placeholder="Ex: Clio, Golf, 308..."
      [required]="true"
      [error]="errors.model"
    ></app-input-field>

    <app-input-field
      label="Kilométrage"
      [value]="data.mileage"
      (valueChange)="onFieldChange('mileage', $event)"
      placeholder="Entrez le kilométrage"
      type="number"
      [required]="true"
      [error]="errors.mileage"
    ></app-input-field>

    <div class="button-container">
      <app-button
        variant="secondary"
        (buttonClick)="onPrevious()"
      >
        Précédent
      </app-button>
      
      <app-button
        variant="primary"
        (buttonClick)="onNext()"
      >
        Suivant
      </app-button>
    </div>
  </div>
</div>
