// src/app/features/repair-order/driver-info/driver-info.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DriverInfo } from '../../../shared/models/repair-order.model';
import { InputFieldComponent } from '../../../shared/components/input-field/input-field.component';
import { ButtonComponent } from '../../../shared/components/button/button.component';

@Component({
  selector: 'app-driver-info',
  standalone: true,
  imports: [
    CommonModule,
    InputFieldComponent,
    ButtonComponent
  ],
  templateUrl: './driver-info.component.html',
  styleUrl: './driver-info.component.scss'
})
export class DriverInfoComponent {
  @Input() data: DriverInfo = {
    firstName: '',
    lastName: '',
    company: ''
  };
  
  @Output() dataChange = new EventEmitter<DriverInfo>();
  @Output() nextStep = new EventEmitter<void>();

  errors = {
    firstName: '',
    lastName: '',
    company: ''
  };

  onFieldChange(field: keyof DriverInfo, value: string): void {
    this.data = { ...this.data, [field]: value };
    this.dataChange.emit(this.data);
    
    if (this.errors[field as keyof typeof this.errors] !== undefined) {
      this.errors[field as keyof typeof this.errors] = '';
    }
  }

  validate(): boolean {
    this.errors = {
      firstName: '',
      lastName: '',
      company: ''
    };

    if (!this.data.firstName.trim()) {
      this.errors.firstName = 'Le prénom est requis';
    }

    if (!this.data.lastName.trim()) {
      this.errors.lastName = 'Le nom est requis';
    }

    if (!this.data.company.trim()) {
      this.errors.company = 'La société est requise';
    }

    return !Object.values(this.errors).some(error => error);
  }

  onNext(): void {
    if (this.validate()) {
      this.nextStep.emit();
    }
  }
}
<div class="driver-info-container">
  <h2 class="page-title">Informations du conducteur</h2>
  
  <div class="form-container">
    <app-input-field
      label="Nom"
      [value]="data.lastName"
      (valueChange)="onFieldChange('lastName', $event)"
      placeholder="Entrez le nom"
      [required]="true"
      [error]="errors.lastName"
    ></app-input-field>

    <app-input-field
      label="Prénom"
      [value]="data.firstName"
      (valueChange)="onFieldChange('firstName', $event)"
      placeholder="Entrez le prénom"
      [required]="true"
      [error]="errors.firstName"
    ></app-input-field>

    <app-input-field
      label="Société"
      [value]="data.company"
      (valueChange)="onFieldChange('company', $event)"
      placeholder="Entrez le nom de la société"
      [required]="true"
      [error]="errors.company"
    ></app-input-field>

    <div class="button-container">
      <app-button
        variant="primary"
        (buttonClick)="onNext()"
      >
        Suivant
      </app-button>
    </div>
  </div>
</div>

// 004bb18f-ba0c-4cae-b281-4740b6c51221/src/pages/DriverInfo.tsx
import React, { useState } from 'react';
import { InputField } from '../components/InputField';
import { Button } from '../components/Button';
interface DriverData {
  firstName: string;
  lastName: string;
  company: string;
}
interface DriverInfoProps {
  data: DriverData;
  updateData: (data: Partial<DriverData>) => void;
  onNext: () => void;
}
export const DriverInfo = ({
  data,
  updateData,
  onNext
}: DriverInfoProps) => {
  const [errors, setErrors] = useState({
    firstName: '',
    lastName: '',
    company: ''
  });
  const validate = () => {
    const newErrors = {
      firstName: '',
      lastName: '',
      company: ''
    };
    if (!data.firstName.trim()) {
      newErrors.firstName = 'Le prénom est requis';
    }
    if (!data.lastName.trim()) {
      newErrors.lastName = 'Le nom est requis';
    }
    if (!data.company.trim()) {
      newErrors.company = 'La société est requise';
    }
    setErrors(newErrors);
    return !Object.values(newErrors).some(error => error);
  };
  const handleNext = () => {
    if (validate()) {
      onNext();
    }
  };
  return <div className="animate-fadeIn">
      <h2 className="text-2xl font-bold text-[#333333] mb-6">
        Informations du conducteur
      </h2>
      <InputField label="Nom" id="lastName" value={data.lastName} onChange={value => updateData({
      lastName: value
    })} placeholder="Entrez le nom" required error={errors.lastName} />
      <InputField label="Prénom" id="firstName" value={data.firstName} onChange={value => updateData({
      firstName: value
    })} placeholder="Entrez le prénom" required error={errors.firstName} />
      <InputField label="Société" id="company" value={data.company} onChange={value => updateData({
      company: value
    })} placeholder="Entrez le nom de la société" required error={errors.company} />
      <div className="mt-8 flex justify-end">
        <Button onClick={handleNext}>Suivant</Button>
      </div>
    </div>;
};
