// src/app/features/technician/technician-info/technician-info.component.ts
import { Component, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TechnicianInfo } from '../../../shared/models/repair-order.model';
import { InputFieldComponent } from '../../../shared/components/input-field/input-field.component';
import { ButtonComponent } from '../../../shared/components/button/button.component';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'app-technician-info',
  standalone: true,
  imports: [
    CommonModule,
    InputFieldComponent,
    ButtonComponent,
    MatCardModule
  ],
  templateUrl: './technician-info.component.html',
  styleUrl: './technician-info.component.scss'
})
export class TechnicianInfoComponent {
  @Output() submitTechnician = new EventEmitter<TechnicianInfo>();

  techData: TechnicianInfo = {
    name: '',
    date: new Date().toISOString().split('T')[0]
  };

  errors = {
    name: ''
  };

  onNameChange(value: string): void {
    this.techData.name = value;
    if (this.errors.name) {
      this.errors.name = '';
    }
  }

  onDateChange(value: string): void {
    this.techData.date = value;
  }

  validate(): boolean {
    this.errors.name = '';

    if (!this.techData.name.trim()) {
      this.errors.name = 'Le nom est requis';
    }

    return !this.errors.name;
  }

  onSubmit(): void {
    if (this.validate()) {
      this.submitTechnician.emit(this.techData);
    }
  }
}
<div class="technician-container">
    <h2 class="page-title">Identification du technicien</h2>
    
    <mat-card class="info-card">
      <mat-card-content>
        <p class="info-text">
          Veuillez vous identifier pour commencer à saisir des ordres de réparation. 
          Tous les ordres seront associés à votre nom.
        </p>
      </mat-card-content>
    </mat-card>
  
    <div class="form-container">
      <app-input-field
        label="Nom du technicien"
        [value]="techData.name"
        (valueChange)="onNameChange($event)"
        placeholder="Entrez votre nom"
        [required]="true"
        [error]="errors.name"
      ></app-input-field>
  
      <app-input-field
        label="Date d'intervention"
        [value]="techData.date"
        (valueChange)="onDateChange($event)"
        type="date"
      ></app-input-field>
  
      <div class="button-container">
        <app-button
          variant="primary"
          (buttonClick)="onSubmit()"
        >
          Commencer
        </app-button>
      </div>
    </div>
  </div>

// 004bb18f-ba0c-4cae-b281-4740b6c51221/src/pages/TechnicianInfo.tsx
import React, { useState } from 'react';
import { InputField } from '../components/InputField';
import { Button } from '../components/Button';
interface TechnicianInfoProps {
  onSubmit: (data: {
    name: string;
    date: string;
  }) => void;
}
export const TechnicianInfo = ({
  onSubmit
}: TechnicianInfoProps) => {
  const [techData, setTechData] = useState({
    name: '',
    date: new Date().toISOString().split('T')[0]
  });
  const [errors, setErrors] = useState({
    name: ''
  });
  const validate = () => {
    const newErrors = {
      name: ''
    };
    if (!techData.name.trim()) {
      newErrors.name = 'Le nom est requis';
    }
    setErrors(newErrors);
    return !Object.values(newErrors).some(error => error);
  };
  const handleSubmit = () => {
    if (validate()) {
      onSubmit(techData);
    }
  };
  return <div className="animate-fadeIn">
      <h2 className="text-2xl font-bold text-[#333333] mb-6">
        Identification du technicien
      </h2>
      <div className="bg-blue-50 p-4 rounded-lg mb-6 border-l-4 border-[#0054A4]">
        <p className="text-sm text-gray-700">
          Veuillez vous identifier pour commencer à saisir des ordres de
          réparation. Tous les ordres seront associés à votre nom.
        </p>
      </div>
      <InputField label="Nom du technicien" id="techName" value={techData.name} onChange={value => setTechData({
      ...techData,
      name: value
    })} placeholder="Entrez votre nom" required error={errors.name} />
      <InputField label="Date d'intervention" id="techDate" value={techData.date} onChange={value => setTechData({
      ...techData,
      date: value
    })} type="date" />
      <div className="mt-8 flex justify-end">
        <Button onClick={handleSubmit}>Commencer</Button>
      </div>
    </div>;
};
