// src/app/shared/components/car-chassis/car-chassis.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { VehicleCondition } from '../../models/repair-order.model';

@Component({
  selector: 'app-car-chassis',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './car-chassis.component.html',
  styleUrl: './car-chassis.component.scss'
})
export class CarChassisComponent {
  @Input() values: VehicleCondition = {
    frontLeft: '',
    frontRight: '',
    rearLeft: '',
    rearRight: ''
  };
  
  @Output() valuesChange = new EventEmitter<VehicleCondition>();

  onValueChange(position: keyof VehicleCondition, value: string): void {
    const newValues = { ...this.values, [position]: value };
    this.valuesChange.emit(newValues);
  }
}
<div class="car-chassis-container">
  <div class="measurement-layout">
    <!-- Colonne gauche avec inputs -->
    <div class="left-inputs">
      <!-- Avant Gauche (AVG) -->
      <div class="input-group">
        <label class="tire-label">AVG</label>
        <input 
          type="text" 
          [value]="values.frontLeft"
          (input)="onValueChange('frontLeft', $any($event.target).value)"
          placeholder="mm"
          class="tire-input"
        />
      </div>

      <!-- Arrière Gauche (ARG) -->
      <div class="input-group">
        <label class="tire-label">ARG</label>
        <input 
          type="text" 
          [value]="values.rearLeft"
          (input)="onValueChange('rearLeft', $any($event.target).value)"
          placeholder="mm"
          class="tire-input"
        />
      </div>
    </div>

    <!-- Image du véhicule au centre -->
    <div class="car-image-container">
      <img src="/assets/car_vector.png" alt="Vue du dessus du véhicule" class="car-image" />
      <p class="instruction-text">Profondeur sculpture restante (mm)</p>
    </div>

    <!-- Colonne droite avec inputs -->
    <div class="right-inputs">
      <!-- Avant Droit (AVD) -->
      <div class="input-group">
        <label class="tire-label">AVD</label>
        <input 
          type="text" 
          [value]="values.frontRight"
          (input)="onValueChange('frontRight', $any($event.target).value)"
          placeholder="mm"
          class="tire-input"
        />
      </div>

      <!-- Arrière Droit (ARD) -->
      <div class="input-group">
        <label class="tire-label">ARD</label>
        <input 
          type="text" 
          [value]="values.rearRight"
          (input)="onValueChange('rearRight', $any($event.target).value)"
          placeholder="mm"
          class="tire-input"
        />
      </div>
    </div>
  </div>
</div>

// 004bb18f-ba0c-4cae-b281-4740b6c51221/src/components/CarChassis.tsx
import React from 'react';
interface TirePressure {
  frontLeft: string;
  frontRight: string;
  rearLeft: string;
  rearRight: string;
}
interface CarChassisProps {
  values: TirePressure;
  onChange: (position: keyof TirePressure, value: string) => void;
}
export const CarChassis = ({
  values,
  onChange
}: CarChassisProps) => {
  return <div className="relative mx-auto my-8 w-full max-w-md">
      <img src="/ChatGPT_Image_27_juin_2025%2C_18_50_11.png" alt="Car chassis" className="w-full h-auto" />
      {/* Front Left */}
      <div className="absolute top-[20%] left-[15%]">
        <div className="bg-white p-1 rounded-md shadow-md">
          <label className="block text-xs font-medium text-gray-700 mb-1">
            AVG
          </label>
          <input type="text" value={values.frontLeft} onChange={e => onChange('frontLeft', e.target.value)} className="w-16 px-2 py-1 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4]" placeholder="8 mm" />
        </div>
      </div>
      {/* Front Right */}
      <div className="absolute top-[20%] right-[15%]">
        <div className="bg-white p-1 rounded-md shadow-md">
          <label className="block text-xs font-medium text-gray-700 mb-1">
            AVD
          </label>
          <input type="text" value={values.frontRight} onChange={e => onChange('frontRight', e.target.value)} className="w-16 px-2 py-1 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4]" placeholder="8 mm" />
        </div>
      </div>
      {/* Rear Left */}
      <div className="absolute bottom-[20%] left-[15%]">
        <div className="bg-white p-1 rounded-md shadow-md">
          <label className="block text-xs font-medium text-gray-700 mb-1">
            ARG
          </label>
          <input type="text" value={values.rearLeft} onChange={e => onChange('rearLeft', e.target.value)} className="w-16 px-2 py-1 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4]" placeholder="8 mm" />
        </div>
      </div>
      {/* Rear Right */}
      <div className="absolute bottom-[20%] right-[15%]">
        <div className="bg-white p-1 rounded-md shadow-md">
          <label className="block text-xs font-medium text-gray-700 mb-1">
            ARD
          </label>
          <input type="text" value={values.rearRight} onChange={e => onChange('rearRight', e.target.value)} className="w-16 px-2 py-1 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4]" placeholder="8 mm" />
        </div>
      </div>
    </div>;
};
