// proto/src/pages/RepairOrderSummary.tsx
import React from 'react';
import { Button } from '../components/Button';
import { ArrowLeftIcon, SendIcon, PrinterIcon } from 'lucide-react';
interface RepairOrderSummaryProps {
  repairOrders: Array<any>;
  onBack: () => void;
  onSendForBilling: () => void;
}
export const RepairOrderSummary = ({
  repairOrders,
  onBack,
  onSendForBilling
}: RepairOrderSummaryProps) => {
  // Group repair orders by company
  const ordersByCompany = repairOrders.reduce((acc, order) => {
    const company = order.driver.company || 'Particulier';
    if (!acc[company]) {
      acc[company] = [];
    }
    acc[company].push(order);
    return acc;
  }, {});
  // Calculate totals
  const totalOrders = repairOrders.length;
  const totalCompanies = Object.keys(ordersByCompany).length;
  return <div className="animate-fadeIn">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-[#333333]">
          Récapitulatif des ordres
        </h2>
        <button onClick={onBack} className="text-[#0054A4] hover:underline flex items-center">
          <ArrowLeftIcon className="w-4 h-4 mr-1" />
          Retour
        </button>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <div className="bg-blue-50 p-4 rounded-lg">
          <p className="text-sm text-gray-600">Total des ordres</p>
          <p className="text-2xl font-bold text-[#0054A4]">{totalOrders}</p>
        </div>
        <div className="bg-blue-50 p-4 rounded-lg">
          <p className="text-sm text-gray-600">Entreprises</p>
          <p className="text-2xl font-bold text-[#0054A4]">{totalCompanies}</p>
        </div>
        <div className="bg-blue-50 p-4 rounded-lg">
          <p className="text-sm text-gray-600">Date</p>
          <p className="text-2xl font-bold text-[#0054A4]">
            {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
      {Object.entries(ordersByCompany).map(([company, orders]) => <div key={company} className="mb-6 bg-white border rounded-lg shadow-sm overflow-hidden">
          <div className="bg-gray-50 p-3 border-b">
            <h3 className="font-medium">{company}</h3>
            <p className="text-sm text-gray-600">
              {orders.length} ordres de réparation
            </p>
          </div>
          <div className="p-3">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b">
                  <th className="text-left py-2 px-2">Conducteur</th>
                  <th className="text-left py-2 px-2">Véhicule</th>
                  <th className="text-left py-2 px-2">Immatriculation</th>
                  <th className="text-left py-2 px-2">Pneumatiques</th>
                </tr>
              </thead>
              <tbody>
                {orders.map(order => <tr key={order.id} className="border-b hover:bg-gray-50">
                    <td className="py-2 px-2">
                      {order.driver.firstName} {order.driver.lastName}
                    </td>
                    <td className="py-2 px-2">{order.vehicle.brand}</td>
                    <td className="py-2 px-2">{order.vehicle.registration}</td>
                    <td className="py-2 px-2">
                      {order.tires.front && `AV: ${order.tires.front === 'summer' ? 'Été' : order.tires.front === 'winter' ? 'Hiver' : '4 Saisons'}`}
                      {order.tires.front && order.tires.rear && ', '}
                      {order.tires.rear && `AR: ${order.tires.rear === 'summer' ? 'Été' : order.tires.rear === 'winter' ? 'Hiver' : '4 Saisons'}`}
                    </td>
                  </tr>)}
              </tbody>
            </table>
          </div>
        </div>)}
      <div className="mt-8 flex justify-between">
        <Button variant="secondary" onClick={() => window.print()}>
          <PrinterIcon className="w-4 h-4 mr-2" />
          Imprimer
        </Button>
        <Button onClick={onSendForBilling}>
          <SendIcon className="w-4 h-4 mr-2" />
          Envoyer pour facturation
        </Button>
      </div>
    </div>;
};

// src/app/features/dashboard/repair-order-summary/repair-order-summary.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RepairOrder } from '../../../shared/models/repair-order.model';
import { ButtonComponent } from '../../../shared/components/button/button.component';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-repair-order-summary',
  standalone: true,
  imports: [
    CommonModule,
    ButtonComponent,
    MatCardModule,
    MatTableModule,
    MatIconModule
  ],
  templateUrl: './repair-order-summary.component.html',
  styleUrl: './repair-order-summary.component.scss'
})
export class RepairOrderSummaryComponent {
  @Input() repairOrders: RepairOrder[] = [];
  
  @Output() backToDashboard = new EventEmitter<void>();
  @Output() sendForBilling = new EventEmitter<void>();

  // Ajouter cette propriété pour la date
  get currentDate(): Date {
    return new Date();
  }

  get ordersByCompany(): { [company: string]: RepairOrder[] } {
    return this.repairOrders.reduce((acc, order) => {
      const company = order.driver.company || 'Particulier';
      if (!acc[company]) {
        acc[company] = [];
      }
      acc[company].push(order);
      return acc;
    }, {} as { [company: string]: RepairOrder[] });
  }

  get companyEntries(): [string, RepairOrder[]][] {
    return Object.entries(this.ordersByCompany);
  }

  get totalOrders(): number {
    return this.repairOrders.length;
  }

  get totalCompanies(): number {
    return Object.keys(this.ordersByCompany).length;
  }

  onBack(): void {
    this.backToDashboard.emit();
  }

  onSendForBilling(): void {
    this.sendForBilling.emit();
  }

  onPrint(): void {
    window.print();
  }

  getTireTypeLabel(type: string): string {
    switch (type) {
      case 'summer': return 'Été';
      case 'winter': return 'Hiver';
      case 'allSeason': return '4 Saisons';
      default: return type;
    }
  }
}
<div class="summary-container">
    <div class="summary-header">
      <h2 class="page-title">Récapitulatif des ordres</h2>
      <button 
        class="back-button"
        (click)="onBack()"
      >
        <mat-icon>arrow_back</mat-icon>
        Retour
      </button>
    </div>
  
    <!-- Statistiques -->
    <div class="stats-grid">
      <mat-card class="stat-card">
        <mat-card-content>
          <p class="stat-label">Total des ordres</p>
          <p class="stat-value">{{ totalOrders }}</p>
        </mat-card-content>
      </mat-card>
  
      <mat-card class="stat-card">
        <mat-card-content>
          <p class="stat-label">Entreprises</p>
          <p class="stat-value">{{ totalCompanies }}</p>
        </mat-card-content>
      </mat-card>
  
      <mat-card class="stat-card">
        <mat-card-content>
          <p class="stat-label">Date</p>
          <p class="stat-value">{{ currentDate | date:'dd/MM/yyyy' }}</p>
        </mat-card-content>
      </mat-card>
    </div>
  
    <!-- Ordres par entreprise -->
    <div *ngFor="let companyEntry of companyEntries" class="company-section">
      <mat-card class="company-card">
        <mat-card-header class="company-header">
          <mat-card-title>{{ companyEntry[0] }}</mat-card-title>
          <mat-card-subtitle>
            {{ companyEntry[1].length }} ordres de réparation
          </mat-card-subtitle>
        </mat-card-header>
  
        <mat-card-content>
          <div class="table-container">
            <table mat-table [dataSource]="companyEntry[1]" class="orders-table">
              <!-- Colonne Conducteur -->
              <ng-container matColumnDef="driver">
                <th mat-header-cell *matHeaderCellDef>Conducteur</th>
                <td mat-cell *matCellDef="let order">
                  {{ order.driver.firstName }} {{ order.driver.lastName }}
                </td>
              </ng-container>
  
              <!-- Colonne Véhicule -->
              <ng-container matColumnDef="vehicle">
                <th mat-header-cell *matHeaderCellDef>Véhicule</th>
                <td mat-cell *matCellDef="let order">
                  {{ order.vehicle.brand }}
                </td>
              </ng-container>
  
              <!-- Colonne Immatriculation -->
              <ng-container matColumnDef="registration">
                <th mat-header-cell *matHeaderCellDef>Immatriculation</th>
                <td mat-cell *matCellDef="let order">
                  {{ order.vehicle.registration }}
                </td>
              </ng-container>
  
              <!-- Colonne Pneumatiques -->
              <ng-container matColumnDef="tires">
                <th mat-header-cell *matHeaderCellDef>Pneumatiques</th>
                <td mat-cell *matCellDef="let order">
                  <span *ngIf="order.tires.front">
                    AV: {{ getTireTypeLabel(order.tires.front) }}
                  </span>
                  <span *ngIf="order.tires.front && order.tires.rear">, </span>
                  <span *ngIf="order.tires.rear">
                    AR: {{ getTireTypeLabel(order.tires.rear) }}
                  </span>
                </td>
              </ng-container>
  
              <tr mat-header-row *matHeaderRowDef="['driver', 'vehicle', 'registration', 'tires']"></tr>
              <tr 
                mat-row 
                *matRowDef="let row; columns: ['driver', 'vehicle', 'registration', 'tires']"
                class="order-row"
              ></tr>
            </table>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  
    <!-- Actions -->
    <div class="actions-section">
      <app-button
        variant="secondary"
        (buttonClick)="onPrint()"
        icon="print"
      >
        Imprimer
      </app-button>
  
      <app-button
        variant="primary"
        (buttonClick)="onSendForBilling()"
        icon="send"
      >
        Envoyer pour facturation
      </app-button>
    </div>
  </div>
