// 004bb18f-ba0c-4cae-b281-4740b6c51221/src/pages/TechnicianDashboard.tsx
import React, { useState } from 'react';
import { Button } from '../components/Button';
import { PlusIcon, SendIcon, FileTextIcon, EditIcon, TrashIcon, ClockIcon, HelpCircleIcon, AlertCircleIcon, CheckCircleIcon, InfoIcon, MapPinIcon, XIcon, SaveIcon, AlertTriangleIcon } from 'lucide-react';
interface TechnicianDashboardProps {
  technicianInfo: {
    name: string;
    date: string;
  };
  repairOrders: Array<any>;
  onStartNew: () => void;
  onEdit: (id: string) => void;
  onUpdate: (order: any) => void;
  onDelete: (id: string) => void;
  onSendForBilling: () => void;
  onViewHistory: () => void;
  onShowHelp: () => void;
}
export const TechnicianDashboard = ({
  technicianInfo,
  repairOrders,
  onStartNew,
  onEdit,
  onUpdate,
  onDelete,
  onSendForBilling,
  onViewHistory,
  onShowHelp
}: TechnicianDashboardProps) => {
  // État pour suivre quel ordre est en cours de modification d'emplacement
  const [editingLocationOrder, setEditingLocationOrder] = useState(null);
  // États pour les valeurs d'emplacement temporaires
  const [tempOutboundLocation, setTempOutboundLocation] = useState('');
  const [tempInboundLocation, setTempInboundLocation] = useState('');
  // État pour la boîte de dialogue de confirmation de suppression
  const [showDeleteConfirmation, setShowDeleteConfirmation] = useState(false);
  // ID de l'ordre à supprimer
  const [orderToDeleteId, setOrderToDeleteId] = useState(null);
  // Commencer la modification d'un emplacement
  const startEditingLocation = order => {
    setEditingLocationOrder(order);
    setTempOutboundLocation(order.storage?.outbound?.location || '');
    setTempInboundLocation(order.storage?.inbound?.location || '');
  };
  // Annuler la modification
  const cancelEditingLocation = () => {
    setEditingLocationOrder(null);
    setTempOutboundLocation('');
    setTempInboundLocation('');
  };
  // Ouvrir la boîte de dialogue de confirmation de suppression
  const confirmDelete = orderId => {
    setOrderToDeleteId(orderId);
    setShowDeleteConfirmation(true);
  };
  // Annuler la suppression
  const cancelDelete = () => {
    setOrderToDeleteId(null);
    setShowDeleteConfirmation(false);
  };
  // Confirmer et exécuter la suppression
  const executeDelete = () => {
    if (orderToDeleteId) {
      onDelete(orderToDeleteId);
      setOrderToDeleteId(null);
      setShowDeleteConfirmation(false);
    }
  };
  // Sauvegarder l'emplacement
  const saveLocation = order => {
    // Créer une copie de l'ordre avec les emplacements mis à jour
    const updatedOrder = {
      ...order
    };
    // Mise à jour des emplacements si nécessaire
    if (order.storage?.outbound?.isBackAtCenter && order.storage?.outbound?.count && order.storage?.outbound?.count !== '0') {
      updatedOrder.storage = {
        ...updatedOrder.storage,
        outbound: {
          ...updatedOrder.storage.outbound,
          location: tempOutboundLocation
        }
      };
    }
    if (order.storage?.inbound?.isBackAtCenter && order.storage?.inbound?.count && order.storage?.inbound?.count !== '0') {
      updatedOrder.storage = {
        ...updatedOrder.storage,
        inbound: {
          ...updatedOrder.storage.inbound,
          location: tempInboundLocation
        }
      };
    }
    // Appeler onUpdate avec l'ordre mis à jour
    onUpdate(updatedOrder);
    // Réinitialiser l'état d'édition
    cancelEditingLocation();
  };
  // Identifier les ordres qui nécessitent une finalisation (emplacement à renseigner)
  const ordersToFinalize = repairOrders.filter(order => {
    // Vérifier si l'ordre a des pneus en entrée ou sortie stock qui sont revenus au centre mais sans emplacement
    const outboundNeedsLocation = order.storage?.outbound?.isBackAtCenter && order.storage?.outbound?.count && order.storage?.outbound?.count !== '0' && !order.storage?.outbound?.location;
    const inboundNeedsLocation = order.storage?.inbound?.isBackAtCenter && order.storage?.inbound?.count && order.storage?.inbound?.count !== '0' && !order.storage?.inbound?.location;
    return outboundNeedsLocation || inboundNeedsLocation;
  });
  // Ordres qui ne nécessitent pas de finalisation
  const regularOrders = repairOrders.filter(order => !ordersToFinalize.includes(order));
  // Group repair orders by company
  const ordersByCompany = regularOrders.reduce((acc, order) => {
    const company = order.driver.company || 'Particulier';
    if (!acc[company]) {
      acc[company] = [];
    }
    acc[company].push(order);
    return acc;
  }, {});
  // Group orders to finalize by company
  const finalizeOrdersByCompany = ordersToFinalize.reduce((acc, order) => {
    const company = order.driver.company || 'Particulier';
    if (!acc[company]) {
      acc[company] = [];
    }
    acc[company].push(order);
    return acc;
  }, {});
  // Vérifier si tous les emplacements sont renseignés pour pouvoir envoyer à la facturation
  const canSendForBilling = () => {
    // Vérifier si tous les ordres qui ont des pneus marqués comme "De retour au centre" ont un emplacement renseigné
    const hasUnfinishedOrders = repairOrders.some(order => {
      const outboundNeedsLocation = order.storage?.outbound?.isBackAtCenter && order.storage?.outbound?.count && order.storage?.outbound?.count !== '0' && !order.storage?.outbound?.location;
      const inboundNeedsLocation = order.storage?.inbound?.isBackAtCenter && order.storage?.inbound?.count && order.storage?.inbound?.count !== '0' && !order.storage?.inbound?.location;
      return outboundNeedsLocation || inboundNeedsLocation;
    });
    return !hasUnfinishedOrders;
  };
  // Gestion de l'envoi pour facturation avec vérification
  const handleSendForBilling = () => {
    if (canSendForBilling()) {
      onSendForBilling();
    } else {
      alert("Impossible d'envoyer pour facturation : certains ordres ont des pneus marqués comme 'De retour au centre' mais l'emplacement n'a pas été renseigné.");
    }
  };
  return <div className="animate-fadeIn">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-[#333333]">
          Tableau de bord technicien
        </h2>
        <div className="text-sm text-gray-600">{technicianInfo.date}</div>
      </div>
      <div className="bg-blue-50 p-4 rounded-lg mb-6 flex items-center justify-between">
        <div className="flex items-center">
          <div className="w-10 h-10 rounded-full bg-[#0054A4] text-white flex items-center justify-center font-bold mr-3">
            {technicianInfo.name.charAt(0)}
          </div>
          <div>
            <p className="font-medium">{technicianInfo.name}</p>
          </div>
        </div>
        <button onClick={onShowHelp} className="flex items-center text-[#0054A4] hover:underline text-sm">
          <HelpCircleIcon className="w-4 h-4 mr-1" />
          Aide
        </button>
      </div>
      <div className="flex flex-wrap gap-4 mb-6">
        <Button onClick={onStartNew}>
          <PlusIcon className="w-4 h-4 mr-2" />
          Nouvel ordre
        </Button>
        <Button variant="secondary" onClick={onViewHistory}>
          <ClockIcon className="w-4 h-4 mr-2" />
          Historique
        </Button>
      </div>
      {/* Section des ordres à finaliser */}
      {ordersToFinalize.length > 0 && <div className="mb-8">
          <div className="flex justify-between items-center mb-4">
            <h3 className="text-lg font-medium text-[#333333] flex items-center">
              <AlertCircleIcon className="w-5 h-5 text-amber-500 mr-2" />
              Ordres à finaliser ({ordersToFinalize.length})
            </h3>
          </div>
          <div className="bg-amber-50 p-4 rounded-lg mb-4 border border-amber-200">
            <p className="text-sm text-amber-800 flex items-center">
              <InfoIcon className="w-4 h-4 mr-2" />
              Ces ordres ont des pneus marqués comme "De retour au centre" mais
              l'emplacement n'a pas été renseigné.
            </p>
          </div>
          {Object.entries(finalizeOrdersByCompany).map(([company, orders]) => <div key={`finalize-${company}`} className="mb-6">
              <h4 className="text-md font-medium text-amber-700 mb-2 border-b border-amber-200 pb-1">
                {company}
              </h4>
              <div className="space-y-3">
                {orders.map(order => <div key={`finalize-${order.id}`} className="bg-white border border-amber-300 rounded-md p-3 shadow-sm hover:shadow-md transition-shadow">
                    {editingLocationOrder && editingLocationOrder.id === order.id ?
            // Mode édition d'emplacement
            <div className="space-y-3">
                        <div className="flex justify-between items-center">
                          <h4 className="font-medium flex items-center">
                            <MapPinIcon className="w-4 h-4 mr-1 text-amber-500" />
                            Renseigner les emplacements
                          </h4>
                          <button onClick={cancelEditingLocation} className="text-gray-500 hover:text-gray-700">
                            <XIcon className="w-4 h-4" />
                          </button>
                        </div>
                        <div className="space-y-3 pt-2">
                          {order.storage?.outbound?.isBackAtCenter && order.storage?.outbound?.count && order.storage?.outbound?.count !== '0' && <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                  Emplacement sortie stock (
                                  {order.storage.outbound.count} pneus)
                                </label>
                                <input type="text" className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-amber-500" value={tempOutboundLocation} onChange={e => setTempOutboundLocation(e.target.value)} placeholder="Ex: Rack A-12" />
                              </div>}
                          {order.storage?.inbound?.isBackAtCenter && order.storage?.inbound?.count && order.storage?.inbound?.count !== '0' && <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                  Emplacement entrée stock (
                                  {order.storage.inbound.count} pneus)
                                </label>
                                <input type="text" className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-amber-500" value={tempInboundLocation} onChange={e => setTempInboundLocation(e.target.value)} placeholder="Ex: Rack B-05" />
                              </div>}
                        </div>
                        <div className="flex justify-end pt-2">
                          <button onClick={() => saveLocation(order)} className="bg-amber-500 hover:bg-amber-600 text-white px-3 py-1.5 rounded-md flex items-center text-sm">
                            <SaveIcon className="w-4 h-4 mr-1" />
                            Enregistrer
                          </button>
                        </div>
                      </div> :
            // Mode affichage normal
            <div className="flex justify-between items-start">
                        <div>
                          <div className="flex items-center">
                            <p className="font-medium">
                              {order.driver.firstName} {order.driver.lastName}
                            </p>
                            <span className="ml-2 px-2 py-0.5 bg-amber-100 text-amber-800 text-xs rounded-full">
                              À finaliser
                            </span>
                          </div>
                          <p className="text-sm text-gray-600">
                            {order.vehicle.brand} - {order.vehicle.registration}
                          </p>
                          <button onClick={() => startEditingLocation(order)} className="mt-2 flex items-center text-xs text-amber-600 hover:text-amber-800 bg-amber-50 hover:bg-amber-100 px-3 py-1.5 rounded-md border border-amber-200 shadow-sm hover:shadow transition-all duration-150 font-medium" aria-label="Cliquez pour renseigner l'emplacement">
                            <MapPinIcon className="w-3 h-3 mr-1" />
                            <EditIcon className="w-2.5 h-2.5 mr-1" />
                            Cliquez pour renseigner l'emplacement
                          </button>
                        </div>
                        <div className="flex space-x-2">
                          <button onClick={() => onEdit(order.id)} className="p-1.5 text-amber-600 hover:bg-amber-50 rounded" title="Éditer cet ordre">
                            <EditIcon className="w-4 h-4" />
                          </button>
                          <button onClick={() => confirmDelete(order.id)} className="p-1.5 text-red-600 hover:bg-red-50 rounded" title="Supprimer cet ordre">
                            <TrashIcon className="w-4 h-4" />
                          </button>
                        </div>
                      </div>}
                  </div>)}
              </div>
            </div>)}
        </div>}
      {/* Section des ordres réguliers */}
      <div className="flex justify-between items-center mb-4">
        <h3 className="text-lg font-medium text-[#333333] flex items-center">
          {ordersToFinalize.length > 0 ? <CheckCircleIcon className="w-5 h-5 text-green-500 mr-2" /> : null}
          Ordres de réparation en cours ({regularOrders.length})
        </h3>
      </div>
      {regularOrders.length === 0 && ordersToFinalize.length === 0 ? <div className="bg-gray-50 rounded-lg p-8 text-center">
          <FileTextIcon className="w-12 h-12 text-gray-400 mx-auto mb-3" />
          <p className="text-gray-500">Aucun ordre de réparation en cours</p>
          <p className="text-sm text-gray-400 mt-1">
            Cliquez sur "Nouvel ordre" pour commencer ou consultez l'historique
          </p>
        </div> : regularOrders.length === 0 ? <div className="bg-gray-50 rounded-lg p-4 text-center">
          <p className="text-gray-500">
            Tous les ordres nécessitent une finalisation
          </p>
        </div> : <>
          {Object.entries(ordersByCompany).map(([company, orders]) => <div key={company} className="mb-6">
              <h4 className="text-md font-medium text-[#0054A4] mb-2 border-b pb-1">
                {company}
              </h4>
              <div className="space-y-3">
                {orders.map(order => <div key={order.id} className="bg-white border rounded-md p-3 shadow-sm hover:shadow-md transition-shadow">
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="font-medium">
                          {order.driver.firstName} {order.driver.lastName}
                        </p>
                        <p className="text-sm text-gray-600">
                          {order.vehicle.brand} - {order.vehicle.registration}
                        </p>
                      </div>
                      <div className="flex space-x-2">
                        <button onClick={() => onEdit(order.id)} className="p-1.5 text-blue-600 hover:bg-blue-50 rounded" title="Éditer cet ordre">
                          <EditIcon className="w-4 h-4" />
                        </button>
                        <button onClick={() => confirmDelete(order.id)} className="p-1.5 text-red-600 hover:bg-red-50 rounded" title="Supprimer cet ordre">
                          <TrashIcon className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  </div>)}
              </div>
            </div>)}
        </>}
      {repairOrders.length > 0 && <div className="mt-8 flex justify-end">
          <Button onClick={handleSendForBilling}>
            <SendIcon className="w-4 h-4 mr-2" />
            Envoyer pour facturation
          </Button>
        </div>}
      {/* Boîte de dialogue de confirmation de suppression */}
      {showDeleteConfirmation && <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full p-6 animate-fadeIn">
            <div className="flex items-center text-red-600 mb-4">
              <AlertTriangleIcon className="w-8 h-8 mr-3" />
              <h3 className="text-lg font-bold">Confirmer la suppression</h3>
            </div>
            <p className="text-gray-700 mb-6">
              Êtes-vous sûr de vouloir supprimer cet ordre de réparation ? Cette
              action est irréversible.
            </p>
            <div className="flex justify-end space-x-3">
              <button onClick={cancelDelete} className="px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50 transition-colors">
                Annuler
              </button>
              <button onClick={executeDelete} className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 transition-colors">
                Supprimer
              </button>
            </div>
          </div>
        </div>}
    </div>;
};

// src/app/features/dashboard/technician-dashboard/technician-dashboard.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RepairOrder, TechnicianInfo } from '../../../shared/models/repair-order.model';
import { ButtonComponent } from '../../../shared/components/button/button.component';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatDialog } from '@angular/material/dialog';
import { FormsModule } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';

@Component({
  selector: 'app-technician-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    ButtonComponent,
    MatCardModule,
    MatIconModule,
    FormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule
  ],
  templateUrl: './technician-dashboard.component.html',
  styleUrls: ['./technician-dashboard.component.scss']
})
export class TechnicianDashboardComponent implements OnChanges {
  @Input() technicianInfo!: TechnicianInfo;
  @Input() repairOrders: RepairOrder[] = [];

  @Output() startNewOrder = new EventEmitter<void>();
  @Output() editOrder = new EventEmitter<string>();
  @Output() updateOrder = new EventEmitter<RepairOrder>();
  @Output() deleteOrder = new EventEmitter<string>();
  @Output() sendForBilling = new EventEmitter<void>();
  @Output() viewHistory = new EventEmitter<void>();
  @Output() showHelp = new EventEmitter<void>();

  ordersToFinalize: RepairOrder[] = [];
  regularOrders: RepairOrder[] = [];
  regularOrdersByCompany: { [company: string]: RepairOrder[] } = {};
  finalizeOrdersByCompany: { [company: string]: RepairOrder[] } = {};
  regularCompanyEntries: [string, RepairOrder[]][] = [];
  finalizeCompanyEntries: [string, RepairOrder[]][] = [];

  editingLocationOrder: RepairOrder | null = null;
  tempOutboundLocation: string = '';
  tempInboundLocation: string = '';

  constructor(public dialog: MatDialog) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['repairOrders']) {
      this.updateOrderLists();
    }
  }

  private updateOrderLists(): void {
    this.ordersToFinalize = this.repairOrders.filter(order => {
      const outboundNeedsLocation = order.storage?.outbound?.isBackAtCenter && order.storage?.outbound?.count && !order.storage?.outbound?.location;
      const inboundNeedsLocation = order.storage?.inbound?.isBackAtCenter && order.storage?.inbound?.count && !order.storage?.inbound?.location;
      return outboundNeedsLocation || inboundNeedsLocation;
    });

    const toFinalizeIds = this.ordersToFinalize.map(o => o.id);
    this.regularOrders = this.repairOrders.filter(order => !toFinalizeIds.includes(order.id));

    this.regularOrdersByCompany = this.groupOrdersByCompany(this.regularOrders);
    this.finalizeOrdersByCompany = this.groupOrdersByCompany(this.ordersToFinalize);
    this.regularCompanyEntries = Object.entries(this.regularOrdersByCompany);
    this.finalizeCompanyEntries = Object.entries(this.finalizeOrdersByCompany);
  }

  private groupOrdersByCompany(orders: RepairOrder[]): { [company: string]: RepairOrder[] } {
    return orders.reduce((acc, order) => {
      const company = order.driver.company || 'Particulier';
      if (!acc[company]) {
        acc[company] = [];
      }
      acc[company].push(order);
      return acc;
    }, {} as { [company: string]: RepairOrder[] });
  }

  startEditingLocation(order: RepairOrder): void {
    this.editingLocationOrder = order;
    this.tempOutboundLocation = order.storage?.outbound?.location || '';
    this.tempInboundLocation = order.storage?.inbound?.location || '';
  }

  cancelEditingLocation(): void {
    this.editingLocationOrder = null;
    this.tempOutboundLocation = '';
    this.tempInboundLocation = '';
  }

  saveLocation(): void {
    if (!this.editingLocationOrder) return;
    const updatedOrder = JSON.parse(JSON.stringify(this.editingLocationOrder));

    if (updatedOrder.storage.outbound?.isBackAtCenter && updatedOrder.storage.outbound?.count) {
      updatedOrder.storage.outbound.location = this.tempOutboundLocation;
    }
    if (updatedOrder.storage.inbound?.isBackAtCenter && updatedOrder.storage.inbound?.count) {
      updatedOrder.storage.inbound.location = this.tempInboundLocation;
    }

    this.updateOrder.emit(updatedOrder);
    this.cancelEditingLocation();
  }

  onStartNew(): void {
    this.startNewOrder.emit();
  }

  onEdit(orderId: string): void {
    this.editOrder.emit(orderId);
  }

  onDelete(orderId: string): void {
    const dialogRef = this.dialog.open(ConfirmDialogComponent, {
      data: {
        title: 'Confirmer la suppression',
        message: 'Êtes-vous sûr de vouloir supprimer cet ordre de réparation ? Cette action est irréversible.'
      }
    });

    dialogRef.afterClosed().subscribe(result => {
      if (result) {
        this.deleteOrder.emit(orderId);
      }
    });
  }

  onSendForBilling(): void {
    if (this.ordersToFinalize.length > 0) {
      alert("Impossible d'envoyer pour facturation : certains ordres ont des emplacements à renseigner.");
      return;
    }
    if (confirm(`Envoyer ${this.repairOrders.length} ordres de réparation pour facturation ?`)) {
      this.sendForBilling.emit();
    }
  }

  onViewHistory(): void {
    this.viewHistory.emit();
  }

  onShowHelp(): void {
    this.showHelp.emit();
  }

  getTireTypeLabel(type: string): string {
    switch (type) {
      case 'summer': return 'Été';
      case 'winter': return 'Hiver';
      case 'allSeason': return '4 Saisons';
      default: return type;
    }
  }
}
<div class="dashboard-container">
  <div class="dashboard-header">
    <h2 class="page-title">Tableau de bord technicien</h2>
    <div class="date-info">{{ technicianInfo.date | date:'dd/MM/yyyy' }}</div>
  </div>

  <mat-card class="technician-card">
    <mat-card-content>
      <div class="technician-info">
        <div class="avatar">{{ technicianInfo.name.charAt(0).toUpperCase() }}</div>
        <div class="tech-details">
          <p class="tech-name">{{ technicianInfo.name }}</p>
          <p class="tech-role">Technicien</p>
        </div>
        <button (click)="onShowHelp()" class="help-button-proto">
          <mat-icon>help_outline</mat-icon>
          <span>Aide</span>
        </button>
      </div>
    </mat-card-content>
  </mat-card>

  <div class="header-buttons-container">
    <app-button variant="primary" (buttonClick)="onStartNew()" icon="add">Nouvel ordre</app-button>
    <app-button variant="secondary" (buttonClick)="onViewHistory()" icon="history">Historique</app-button>
  </div>

  <div *ngIf="ordersToFinalize.length > 0" class="finalize-section">
    <div class="section-header">
      <h3 class="section-title">
        <mat-icon class="finalize-icon">error_outline</mat-icon>
        Ordres à finaliser ({{ ordersToFinalize.length }})
      </h3>
    </div>
    <div class="finalize-info-box">
      Ces ordres ont des pneus marqués comme "De retour au centre" mais l'emplacement n'a pas été renseigné.
    </div>
    <div *ngFor="let companyEntry of finalizeCompanyEntries" class="company-group">
      <h4 class="company-title-finalize">{{ companyEntry[0] }}</h4>
      <div class="orders-list">
        <mat-card *ngFor="let order of companyEntry[1]" class="order-card-finalize">
          <mat-card-content>
            <div *ngIf="editingLocationOrder?.id !== order.id" class="order-content">
              <div class="order-info">
                <p class="driver-name">{{ order.driver.firstName }} {{ order.driver.lastName }} <span class="finalize-badge">À finaliser</span></p>
                <p class="vehicle-info">{{ order.vehicle.brand }} - {{ order.vehicle.registration }}</p>
                <button mat-stroked-button color="warn" (click)="startEditingLocation(order)" class="location-button-mat">
                  <mat-icon>location_on</mat-icon>
                  <span>Cliquez pour renseigner l'emplacement</span>
                </button>
              </div>
              <div class="order-actions">
                <button mat-icon-button (click)="onEdit(order.id)" class="edit-btn" title="Modifier"><mat-icon>edit</mat-icon></button>
                <button mat-icon-button (click)="onDelete(order.id)" class="delete-btn" title="Supprimer"><mat-icon>delete</mat-icon></button>
              </div>
            </div>
            <div *ngIf="editingLocationOrder?.id === order.id" class="location-edit-form">
              <div class="location-edit-header">
                <h4><mat-icon>location_on</mat-icon> Renseigner les emplacements</h4>
                <button mat-icon-button (click)="cancelEditingLocation()" title="Annuler"><mat-icon>close</mat-icon></button>
              </div>
              <div *ngIf="order.storage?.outbound?.isBackAtCenter && order.storage?.outbound?.count">
                <mat-form-field appearance="outline" class="location-input-field">
                  <mat-label>Emplacement sortie stock ({{order.storage.outbound.count}} pneus)</mat-label>
                  <input matInput [(ngModel)]="tempOutboundLocation" placeholder="Ex: Rack A-12">
                </mat-form-field>
              </div>
              <div *ngIf="order.storage?.inbound?.isBackAtCenter && order.storage?.inbound?.count">
                <mat-form-field appearance="outline" class="location-input-field">
                  <mat-label>Emplacement entrée stock ({{order.storage.inbound.count}} pneus)</mat-label>
                  <input matInput [(ngModel)]="tempInboundLocation" placeholder="Ex: Rack B-05">
                </mat-form-field>
              </div>
              <div class="form-actions">
                 <button mat-button (click)="cancelEditingLocation()">Annuler</button>
                 <button mat-flat-button color="warn" (click)="saveLocation()">
                    <mat-icon>save</mat-icon>
                    <span>Enregistrer</span>
                 </button>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  </div>

  <div class="orders-section">
    <div class="section-header">
      <h3 class="section-title">
        <mat-icon class="regular-icon">check_circle_outline</mat-icon>
        Ordres de réparation en cours ({{ regularOrders.length }})
      </h3>
    </div>
    <div *ngIf="repairOrders.length === 0" class="empty-state">
      <mat-icon class="empty-icon">description</mat-icon>
      <p class="empty-text">Aucun ordre de réparation en cours</p>
    </div>
    <div *ngIf="regularOrders.length === 0 && ordersToFinalize.length > 0" class="empty-state">
        <p class="empty-text">Tous les ordres nécessitent une finalisation</p>
    </div>
    <div *ngFor="let companyEntry of regularCompanyEntries" class="company-group">
      <h4 class="company-title">{{ companyEntry[0] }}</h4>
      <div class="orders-list">
        <mat-card *ngFor="let order of companyEntry[1]" class="order-card">
          <mat-card-content>
            <div class="order-content">
              <div class="order-info">
                <p class="driver-name">{{ order.driver.firstName }} {{ order.driver.lastName }}</p>
                <p class="vehicle-info">{{ order.vehicle.brand }} - {{ order.vehicle.registration }}</p>
              </div>
              <div class="order-actions">
                <button mat-icon-button (click)="onEdit(order.id)" class="edit-btn" title="Modifier"><mat-icon>edit</mat-icon></button>
                <button mat-icon-button (click)="onDelete(order.id)" class="delete-btn" title="Supprimer"><mat-icon>delete</mat-icon></button>
              </div>
            </div>
          </mat-card-content>
        </mat-card>
      </div>
    </div>
  </div>

  <div *ngIf="repairOrders.length > 0" class="billing-section">
    <app-button variant="primary" (buttonClick)="onSendForBilling()" icon="send">
      Envoyer pour facturation
    </app-button>
  </div>
</div>
