// proto/src/components/Footer.tsx
import React from 'react';
import { MailIcon } from 'lucide-react';
export const Footer = () => {
  return <footer className="bg-gray-100 py-3 px-4 w-full border-t">
      <div className="max-w-3xl mx-auto flex flex-col md:flex-row justify-between items-center text-sm text-gray-600">
        <div className="mb-2 md:mb-0">
          © {new Date().getFullYear()} Euromaster - Tous droits réservés
        </div>
        <div className="flex items-center">
          <span className="mr-2">Un problème ? Contactez-nous :</span>
          <a href="mailto:jean.paul.benga@euromaster.com" className="text-[#0054A4] hover:underline flex items-center">
            <MailIcon className="w-4 h-4 mr-1" />
            jean.paul.benga@euromaster.com
          </a>
        </div>
      </div>
    </footer>;
};

// src/app/shared/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [MatIconModule],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {
  currentYear = new Date().getFullYear();
}
<footer class="footer-container">
    <div class="footer-content">
      <div class="copyright-text">
        © {{ currentYear }} Euromaster - Tous droits réservés
      </div>
      <div class="contact-section">
        <span>Un problème ? Contactez-nous :</span>
        <a href="mailto:jean.paul.benga&#64;euromaster.com" class="contact-link">
          <mat-icon>email</mat-icon>
          <span>jean.paul.benga&#64;euromaster.com</span>
        </a>
      </div>
    </div>
  </footer>
