// src/app/features/repair-order/storage/storage.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { StorageInfo } from '../../../shared/models/repair-order.model';
import { CheckboxComponent } from '../../../shared/components/checkbox/checkbox.component';
import { InputFieldComponent } from '../../../shared/components/input-field/input-field.component';
import { ButtonComponent } from '../../../shared/components/button/button.component';

@Component({
  selector: 'app-storage',
  standalone: true,
  imports: [
    CommonModule,
    CheckboxComponent,
    InputFieldComponent,
    ButtonComponent
  ],
  templateUrl: './storage.component.html',
  styleUrl: './storage.component.scss'
})
export class StorageComponent {
  @Input() data: StorageInfo = {
    outbound: {
      count: '',
      wheel: false,
      hubcap: false,
      screws: false,
      location: '',
      profile: '',
      dimension: '',
      brand: '',
      tireProfile: '',
      isBackAtCenter: false
    },
    inbound: {
      count: '',
      wheel: false,
      hubcap: false,
      screws: false,
      location: '',
      profile: '',
      dimension: '',
      brand: '',
      tireProfile: '',
      isBackAtCenter: false
    }
  };
  
  @Output() dataChange = new EventEmitter<StorageInfo>();
  @Output() previousStep = new EventEmitter<void>();
  @Output() finishOrder = new EventEmitter<void>();

  errors = {
    inboundBrand: '',
    inboundTireProfile: '',
    inboundDimension: ''
  };

  get completeData(): StorageInfo {
    return {
      outbound: {
        count: this.data.outbound?.count || '',
        wheel: this.data.outbound?.wheel || false,
        hubcap: this.data.outbound?.hubcap || false,
        screws: this.data.outbound?.screws || false,
        location: this.data.outbound?.location || '',
        profile: this.data.outbound?.profile || '',
        dimension: this.data.outbound?.dimension || '',
        brand: this.data.outbound?.brand || '',
        tireProfile: this.data.outbound?.tireProfile || '',
        isBackAtCenter: this.data.outbound?.isBackAtCenter || false
      },
      inbound: {
        count: this.data.inbound?.count || '',
        wheel: this.data.inbound?.wheel || false,
        hubcap: this.data.inbound?.hubcap || false,
        screws: this.data.inbound?.screws || false,
        location: this.data.inbound?.location || '',
        profile: this.data.inbound?.profile || '',
        dimension: this.data.inbound?.dimension || '',
        brand: this.data.inbound?.brand || '',
        tireProfile: this.data.inbound?.tireProfile || '',
        isBackAtCenter: this.data.inbound?.isBackAtCenter || false
      }
    };
  }

  updateOutboundData(outboundData: any): void {
    const newData = {
      ...this.data,
      outbound: {
        ...this.completeData.outbound,
        ...outboundData
      }
    };
    this.dataChange.emit(newData);
  }

  updateInboundData(inboundData: any): void {
    const newData = {
      ...this.data,
      inbound: {
        ...this.completeData.inbound,
        ...inboundData
      }
    };
    this.dataChange.emit(newData);
  }

  validate(): boolean {
    this.errors = {
      inboundBrand: '',
      inboundTireProfile: '',
      inboundDimension: ''
    };

    if (this.completeData.inbound.count && this.completeData.inbound.count !== '0') {
      if (!this.completeData.inbound.brand) {
        this.errors.inboundBrand = "La marque est requise pour l'entrée stock";
      }
      if (!this.completeData.inbound.tireProfile) {
        this.errors.inboundTireProfile = "Le profil est requis pour l'entrée stock";
      }
      if (!this.completeData.inbound.dimension) {
        this.errors.inboundDimension = "La dimension est requise pour l'entrée stock";
      }
    }

    return !Object.values(this.errors).some(error => error);
  }

  onPrevious(): void {
    this.previousStep.emit();
  }

  onFinish(): void {
    if (this.validate()) {
      this.finishOrder.emit();
    }
  }
}
<div class="storage-container">
  <h2 class="page-title">GARDIENNAGE</h2>
  
  <div class="info-section">
    <p class="info-text">
      Le champ "Emplacement" ne peut être renseigné qu'une fois de retour
      au centre. Veuillez cocher la case "De retour au centre" pour
      activer ce champ.
    </p>
  </div>

  <div class="form-container">
    <div class="storage-grid">
      <!-- Section Sortie Stock -->
      <div class="storage-section">
        <h3 class="section-title">Sortie stock</h3>
        
        <div class="section-content">
          <app-input-field
            label="Nombre de pneus"
            [value]="completeData.outbound.count"
            (valueChange)="updateOutboundData({ count: $event })"
            placeholder="Nombre de pneus en sortie"
            type="number"
          ></app-input-field>

          <div *ngIf="completeData.outbound.count && completeData.outbound.count !== '0'" class="details-section">
            <div class="checkbox-group">
              <app-checkbox
                label="Roue"
                [checked]="completeData.outbound.wheel"
                (checkedChange)="updateOutboundData({ wheel: $event })"
              ></app-checkbox>
              <app-checkbox
                label="Enjoliveur"
                [checked]="completeData.outbound.hubcap"
                (checkedChange)="updateOutboundData({ hubcap: $event })"
              ></app-checkbox>
              <app-checkbox
                label="Visserie"
                [checked]="completeData.outbound.screws"
                (checkedChange)="updateOutboundData({ screws: $event })"
              ></app-checkbox>
            </div>

            <app-input-field
              label="Marque"
              [value]="completeData.outbound.brand"
              (valueChange)="updateOutboundData({ brand: $event })"
              placeholder="Michelin"
            ></app-input-field>

            <app-input-field
              label="Profil"
              [value]="completeData.outbound.tireProfile"
              (valueChange)="updateOutboundData({ tireProfile: $event })"
              placeholder="Primacy 5"
            ></app-input-field>

            <app-input-field
              label="Dimension"
              [value]="completeData.outbound.dimension"
              (valueChange)="updateOutboundData({ dimension: $event })"
              placeholder="Ex: 205/55R16"
            ></app-input-field>

            <app-input-field
              label="Profondeur des sculptures (mm)"
              [value]="completeData.outbound.profile"
              (valueChange)="updateOutboundData({ profile: $event })"
              placeholder="Mesure en mm"
            ></app-input-field>

            <div class="back-at-center-section">
              <app-checkbox
                label="De retour au centre"
                [checked]="completeData.outbound.isBackAtCenter"
                (checkedChange)="updateOutboundData({ isBackAtCenter: $event })"
              ></app-checkbox>
            </div>

            <div class="location-field" [class.disabled]="!completeData.outbound.isBackAtCenter">
              <app-input-field
                label="Emplacement"
                [value]="completeData.outbound.location"
                (valueChange)="updateOutboundData({ location: $event })"
                placeholder="Précisez l'emplacement"
                [disabled]="!completeData.outbound.isBackAtCenter"
              ></app-input-field>
              <p *ngIf="!completeData.outbound.isBackAtCenter" class="location-note">
                L'emplacement sera à renseigner une fois de retour au centre
              </p>
            </div>
          </div>
        </div>
      </div>

      <!-- Section Entrée Stock -->
      <div class="storage-section">
        <h3 class="section-title">Entrée stock</h3>
        
        <div class="section-content">
          <app-input-field
            label="Nombre de pneus"
            [value]="completeData.inbound.count"
            (valueChange)="updateInboundData({ count: $event })"
            placeholder="Nombre de pneus en entrée"
            type="number"
          ></app-input-field>

          <div *ngIf="completeData.inbound.count && completeData.inbound.count !== '0'" class="details-section">
            <div class="checkbox-group">
              <app-checkbox
                label="Roue"
                [checked]="completeData.inbound.wheel"
                (checkedChange)="updateInboundData({ wheel: $event })"
              ></app-checkbox>
              <app-checkbox
                label="Enjoliveur"
                [checked]="completeData.inbound.hubcap"
                (checkedChange)="updateInboundData({ hubcap: $event })"
              ></app-checkbox>
              <app-checkbox
                label="Visserie"
                [checked]="completeData.inbound.screws"
                (checkedChange)="updateInboundData({ screws: $event })"
              ></app-checkbox>
            </div>

            <app-input-field
              label="Marque"
              [value]="completeData.inbound.brand"
              (valueChange)="updateInboundData({ brand: $event })"
              placeholder="Michelin"
              [required]="true"
              [error]="errors.inboundBrand"
            ></app-input-field>

            <app-input-field
              label="Profil"
              [value]="completeData.inbound.tireProfile"
              (valueChange)="updateInboundData({ tireProfile: $event })"
              placeholder="Primacy 5"
              [required]="true"
              [error]="errors.inboundTireProfile"
            ></app-input-field>

            <app-input-field
              label="Dimension"
              [value]="completeData.inbound.dimension"
              (valueChange)="updateInboundData({ dimension: $event })"
              placeholder="Ex: 205/55R16"
              [required]="true"
              [error]="errors.inboundDimension"
            ></app-input-field>

            <app-input-field
              label="Profondeur des sculptures (mm)"
              [value]="completeData.inbound.profile"
              (valueChange)="updateInboundData({ profile: $event })"
              placeholder="Mesure en mm"
            ></app-input-field>

            <div class="back-at-center-section">
              <app-checkbox
                label="De retour au centre"
                [checked]="completeData.inbound.isBackAtCenter"
                (checkedChange)="updateInboundData({ isBackAtCenter: $event })"
              ></app-checkbox>
            </div>

            <div class="location-field" [class.disabled]="!completeData.inbound.isBackAtCenter">
              <app-input-field
                label="Emplacement"
                [value]="completeData.inbound.location"
                (valueChange)="updateInboundData({ location: $event })"
                placeholder="Précisez l'emplacement"
                [disabled]="!completeData.inbound.isBackAtCenter"
              ></app-input-field>
              <p *ngIf="!completeData.inbound.isBackAtCenter" class="location-note">
                L'emplacement sera à renseigner une fois de retour au centre
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="button-container">
      <app-button
        variant="secondary"
        (buttonClick)="onPrevious()"
      >
        Précédent
      </app-button>
      
      <app-button
        variant="primary"
        (buttonClick)="onFinish()"
        icon="check"
      >
        Finaliser
      </app-button>
    </div>
  </div>
</div>

// proto/src/pages/Storage.tsx
import React, { useState } from 'react';
import { Checkbox } from '../components/Checkbox';
import { InputField } from '../components/InputField';
import { Button } from '../components/Button';
import { InfoIcon } from 'lucide-react';
interface StorageData {
  outbound: {
    count: string;
    wheel: boolean;
    hubcap: boolean;
    screws: boolean;
    location: string;
    profile: string;
    dimension: string;
    brand: string;
    tireProfile: string;
    isBackAtCenter: boolean;
  };
  inbound: {
    count: string;
    wheel: boolean;
    hubcap: boolean;
    screws: boolean;
    location: string;
    profile: string;
    dimension: string;
    brand: string;
    tireProfile: string;
    isBackAtCenter: boolean;
  };
}
interface StorageProps {
  data: StorageData;
  updateData: (data: Partial<StorageData>) => void;
  onPrevious: () => void;
  onFinish: () => void;
}
export const Storage = ({
  data,
  updateData,
  onPrevious,
  onFinish
}: StorageProps) => {
  // Initialiser les données manquantes avec des valeurs par défaut
  const completeData = {
    outbound: {
      count: data.outbound?.count || '',
      wheel: data.outbound?.wheel || false,
      hubcap: data.outbound?.hubcap || false,
      screws: data.outbound?.screws || false,
      location: data.outbound?.location || '',
      profile: data.outbound?.profile || '',
      dimension: data.outbound?.dimension || '',
      brand: data.outbound?.brand || '',
      tireProfile: data.outbound?.tireProfile || '',
      isBackAtCenter: data.outbound?.isBackAtCenter || false
    },
    inbound: {
      count: data.inbound?.count || '',
      wheel: data.inbound?.wheel || false,
      hubcap: data.inbound?.hubcap || false,
      screws: data.inbound?.screws || false,
      location: data.inbound?.location || '',
      profile: data.inbound?.profile || '',
      dimension: data.inbound?.dimension || '',
      brand: data.inbound?.brand || '',
      tireProfile: data.inbound?.tireProfile || '',
      isBackAtCenter: data.inbound?.isBackAtCenter || false
    }
  };
  const [errors, setErrors] = useState({
    inboundBrand: '',
    inboundTireProfile: '',
    inboundDimension: ''
  });
  const updateOutboundData = outboundData => {
    updateData({
      outbound: {
        ...completeData.outbound,
        ...outboundData
      }
    });
  };
  const updateInboundData = inboundData => {
    updateData({
      inbound: {
        ...completeData.inbound,
        ...inboundData
      }
    });
  };
  const validate = () => {
    const newErrors = {
      inboundBrand: '',
      inboundTireProfile: '',
      inboundDimension: ''
    };
    // Validation conditionnelle pour l'entrée stock
    if (completeData.inbound.count && completeData.inbound.count !== '0') {
      if (!completeData.inbound.brand) {
        newErrors.inboundBrand = "La marque est requise pour l'entrée stock";
      }
      if (!completeData.inbound.tireProfile) {
        newErrors.inboundTireProfile = "Le profil est requis pour l'entrée stock";
      }
      if (!completeData.inbound.dimension) {
        newErrors.inboundDimension = "La dimension est requise pour l'entrée stock";
      }
    }
    setErrors(newErrors);
    return !Object.values(newErrors).some(error => error);
  };
  const handleFinish = () => {
    if (validate()) {
      onFinish();
    }
  };
  return <div className="animate-fadeIn">
      <h2 className="text-2xl font-bold text-[#333333] mb-6">GARDIENNAGE</h2>
      <div className="bg-blue-50 p-4 rounded-lg mb-6 border-l-4 border-[#0054A4]">
        <div className="flex items-start">
          <InfoIcon className="w-5 h-5 text-[#0054A4] mr-2 mt-0.5" />
          <p className="text-sm text-gray-700">
            Le champ "Emplacement" ne peut être renseigné qu'une fois de retour
            au centre. Veuillez cocher la case "De retour au centre" pour
            activer ce champ.
          </p>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        {/* Section Sortie Stock */}
        <div className="bg-gray-50 p-4 rounded-lg border">
          <h3 className="text-lg font-medium text-[#0054A4] mb-4">
            Sortie stock
          </h3>
          <div className="space-y-4">
            <InputField label="Nombre de pneus" id="outboundCount" value={completeData.outbound.count} onChange={value => updateOutboundData({
            count: value
          })} placeholder="Nombre de pneus en sortie" type="number" />
            {completeData.outbound.count && completeData.outbound.count !== '0' && <>
                  <div className="ml-4 space-y-3">
                    <Checkbox label="Roue" id="outboundWheel" checked={completeData.outbound.wheel} onChange={checked => updateOutboundData({
                wheel: checked
              })} />
                    <Checkbox label="Enjoliveur" id="outboundHubcap" checked={completeData.outbound.hubcap} onChange={checked => updateOutboundData({
                hubcap: checked
              })} />
                    <Checkbox label="Visserie" id="outboundScrews" checked={completeData.outbound.screws} onChange={checked => updateOutboundData({
                screws: checked
              })} />
                  </div>
                  <InputField label="Marque" id="outboundBrand" value={completeData.outbound.brand} onChange={value => updateOutboundData({
              brand: value
            })} placeholder="Michelin" />
                  <InputField label="Profil" id="outboundTireProfile" value={completeData.outbound.tireProfile} onChange={value => updateOutboundData({
              tireProfile: value
            })} placeholder="Primacy 5" />
                  <InputField label="Dimension" id="outboundDimension" value={completeData.outbound.dimension} onChange={value => updateOutboundData({
              dimension: value
            })} placeholder="Ex: 205/55R16" />
                  <InputField label="Profondeur des sculptures (mm)" id="outboundProfile" value={completeData.outbound.profile} onChange={value => updateOutboundData({
              profile: value
            })} placeholder="Mesure en mm" />
                  <div className="pt-2 border-t border-gray-200">
                    <Checkbox label="De retour au centre" id="outboundBackAtCenter" checked={completeData.outbound.isBackAtCenter} onChange={checked => updateOutboundData({
                isBackAtCenter: checked
              })} />
                  </div>
                  <InputField label="Emplacement" id="outboundLocation" value={completeData.outbound.location} onChange={value => updateOutboundData({
              location: value
            })} placeholder="Précisez l'emplacement" disabled={!completeData.outbound.isBackAtCenter} className={!completeData.outbound.isBackAtCenter ? 'opacity-50' : ''} />
                  {!completeData.outbound.isBackAtCenter && <p className="text-xs text-gray-500 italic">
                      L'emplacement sera à renseigner une fois de retour au
                      centre
                    </p>}
                </>}
          </div>
        </div>
        {/* Section Entrée Stock */}
        <div className="bg-gray-50 p-4 rounded-lg border">
          <h3 className="text-lg font-medium text-[#0054A4] mb-4">
            Entrée stock
          </h3>
          <div className="space-y-4">
            <InputField label="Nombre de pneus" id="inboundCount" value={completeData.inbound.count} onChange={value => updateInboundData({
            count: value
          })} placeholder="Nombre de pneus en entrée" type="number" />
            {completeData.inbound.count && completeData.inbound.count !== '0' && <>
                  <div className="ml-4 space-y-3">
                    <Checkbox label="Roue" id="inboundWheel" checked={completeData.inbound.wheel} onChange={checked => updateInboundData({
                wheel: checked
              })} />
                    <Checkbox label="Enjoliveur" id="inboundHubcap" checked={completeData.inbound.hubcap} onChange={checked => updateInboundData({
                hubcap: checked
              })} />
                    <Checkbox label="Visserie" id="inboundScrews" checked={completeData.inbound.screws} onChange={checked => updateInboundData({
                screws: checked
              })} />
                  </div>
                  <InputField label="Marque" id="inboundBrand" value={completeData.inbound.brand} onChange={value => updateInboundData({
              brand: value
            })} placeholder="Michelin" required error={errors.inboundBrand} />
                  <InputField label="Profil" id="inboundTireProfile" value={completeData.inbound.tireProfile} onChange={value => updateInboundData({
              tireProfile: value
            })} placeholder="Primacy 5" required error={errors.inboundTireProfile} />
                  <InputField label="Dimension" id="inboundDimension" value={completeData.inbound.dimension} onChange={value => updateInboundData({
              dimension: value
            })} placeholder="Ex: 205/55R16" required error={errors.inboundDimension} />
                  <InputField label="Profondeur des sculptures (mm)" id="inboundProfile" value={completeData.inbound.profile} onChange={value => updateInboundData({
              profile: value
            })} placeholder="Mesure en mm" />
                  <div className="pt-2 border-t border-gray-200">
                    <Checkbox label="De retour au centre" id="inboundBackAtCenter" checked={completeData.inbound.isBackAtCenter} onChange={checked => updateInboundData({
                isBackAtCenter: checked
              })} />
                  </div>
                  <InputField label="Emplacement" id="inboundLocation" value={completeData.inbound.location} onChange={value => updateInboundData({
              location: value
            })} placeholder="Précisez l'emplacement" disabled={!completeData.inbound.isBackAtCenter} className={!completeData.inbound.isBackAtCenter ? 'opacity-50' : ''} />
                  {!completeData.inbound.isBackAtCenter && <p className="text-xs text-gray-500 italic">
                      L'emplacement sera à renseigner une fois de retour au
                      centre
                    </p>}
                </>}
          </div>
        </div>
      </div>
      <div className="mt-8 flex justify-between">
        <Button onClick={onPrevious} variant="secondary">
          Précédent
        </Button>
        <Button onClick={handleFinish}>Finaliser</Button>
      </div>
    </div>;
};
