// src/app/features/repair-order/tire-selection/tire-selection.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TireInfo } from '../../../shared/models/repair-order.model';
import { ButtonComponent } from '../../../shared/components/button/button.component';
import { CheckboxComponent } from '../../../shared/components/checkbox/checkbox.component';
import { InputFieldComponent } from '../../../shared/components/input-field/input-field.component';

@Component({
  selector: 'app-tire-selection',
  standalone: true,
  imports: [
    CommonModule,
    ButtonComponent,
    CheckboxComponent,
    InputFieldComponent
  ],
  templateUrl: './tire-selection.component.html',
  styleUrl: './tire-selection.component.scss'
})
export class TireSelectionComponent {
  @Input() data: TireInfo = {
    front: '',
    rear: '',
    frontBrand: '',
    rearBrand: '',
    frontModel: '',
    rearModel: '',
    frontDimension: '',
    rearDimension: '',
    frontIndex: '',
    rearIndex: '',
    frontTireCount: '',
    rearTireCount: '',
    tireInsurance: false,
    roadAssistance: false,
    valveReuse: false,
    valveMaintenance: false,
    balancingType: false,
    geometryType: false,
    contReg: false,
    wasteAgreementCount: '',
    laborCount: '',
    valveCount: '',
    nitrogenCount: '',
    punctureRepairCount: '',
    mountingCount: '',
    rotationCount: ''
  };
  
  @Output() dataChange = new EventEmitter<TireInfo>();
  @Output() nextStep = new EventEmitter<void>();
  @Output() previousStep = new EventEmitter<void>();

  showServices = false;
  showOptions = false;

  errors = {
    frontBrand: '',
    rearBrand: '',
    frontModel: '',
    rearModel: '',
    frontDimension: '',
    rearDimension: '',
    frontTireCount: '',
    rearTireCount: '',
    laborCount: '',
    valveCount: ''
  };

  onFieldChange(field: keyof TireInfo, value: string | boolean): void {
    this.data = { ...this.data, [field]: value };
    this.dataChange.emit(this.data);
    
    if (typeof value === 'string' && this.errors[field as keyof typeof this.errors] !== undefined) {
      this.errors[field as keyof typeof this.errors] = '';
    }
  }

  copyFrontBrandToRear(): void {
    this.onFieldChange('rearBrand', this.data.frontBrand);
  }

  copyFrontModelToRear(): void {
    this.onFieldChange('rearModel', this.data.frontModel);
  }

  copyFrontDimensionToRear(): void {
    this.onFieldChange('rearDimension', this.data.frontDimension);
  }

  copyFrontIndexToRear(): void {
    this.onFieldChange('rearIndex', this.data.frontIndex);
  }

  copyAllFrontToRear(): void {
    this.data = {
      ...this.data,
      rear: this.data.front,
      rearBrand: this.data.frontBrand,
      rearModel: this.data.frontModel,
      rearDimension: this.data.frontDimension,
      rearIndex: this.data.frontIndex,
      rearTireCount: this.data.frontTireCount
    };
    this.dataChange.emit(this.data);
  }

  toggleServices(): void {
    this.showServices = !this.showServices;
  }

  toggleOptions(): void {
    this.showOptions = !this.showOptions;
  }

  validate(): boolean {
    this.errors = {
      frontBrand: '',
      rearBrand: '',
      frontModel: '',
      rearModel: '',
      frontDimension: '',
      rearDimension: '',
      frontTireCount: '',
      rearTireCount: '',
      laborCount: '',
      valveCount: ''
    };

    if (this.data.frontTireCount && this.data.frontTireCount !== '0') {
      if (!this.data.frontBrand) {
        this.errors.frontBrand = 'La marque est requise';
      }
      if (!this.data.frontModel) {
        this.errors.frontModel = 'Le profil est requis';
      }
      if (!this.data.frontDimension) {
        this.errors.frontDimension = 'La dimension est requise';
      }
    }

    if (this.data.rearTireCount && this.data.rearTireCount !== '0') {
      if (!this.data.rearBrand) {
        this.errors.rearBrand = 'La marque est requise';
      }
      if (!this.data.rearModel) {
        this.errors.rearModel = 'Le profil est requis';
      }
      if (!this.data.rearDimension) {
        this.errors.rearDimension = 'La dimension est requise';
      }
    }

    if (!this.data.frontTireCount && !this.data.rearTireCount) {
      this.errors.frontTireCount = 'Le nombre de pneus est requis';
      this.errors.rearTireCount = 'Le nombre de pneus est requis';
    }

    if (!this.data.laborCount) {
      this.errors.laborCount = 'Le forfait MO est requis';
    }

    if (!this.data.valveCount) {
      this.errors.valveCount = 'La valve est requise';
    }

    return !Object.values(this.errors).some(error => error);
  }

  onNext(): void {
    if (this.validate()) {
      this.nextStep.emit();
    }
  }

  onPrevious(): void {
    this.previousStep.emit();
  }
}
<div class="tire-selection-container">
  <h2 class="page-title">PNEUMATIQUES</h2>
  
  <div class="form-container">
    <div class="tires-grid">
      <!-- PNEU AV -->
      <div class="tire-section">
        <h3 class="section-title">PNEU AV</h3>
        
        <div class="tire-type-row">
          <app-checkbox
            label="Été"
            [checked]="data.front === 'summer'"
            (checkedChange)="onFieldChange('front', $event ? 'summer' : '')"
          ></app-checkbox>
          <app-checkbox
            label="Toutes Saisons"
            [checked]="data.front === 'allSeason'"
            (checkedChange)="onFieldChange('front', $event ? 'allSeason' : '')"
          ></app-checkbox>
          <app-checkbox
            label="Hiver"
            [checked]="data.front === 'winter'"
            (checkedChange)="onFieldChange('front', $event ? 'winter' : '')"
          ></app-checkbox>
        </div>
        
        <app-input-field
          label="Marque"
          [value]="data.frontBrand"
          (valueChange)="onFieldChange('frontBrand', $event)"
          placeholder="Michelin"
          [required]="!!data.frontTireCount && data.frontTireCount !== '0'"
          [error]="errors.frontBrand"
        ></app-input-field>
        
        <app-input-field
          label="Profil"
          [value]="data.frontModel"
          (valueChange)="onFieldChange('frontModel', $event)"
          placeholder="Primacy 5"
          [required]="!!data.frontTireCount && data.frontTireCount !== '0'"
          [error]="errors.frontModel"
        ></app-input-field>
        
        <div class="dimension-row">
          <app-input-field
            label="Dimension"
            [value]="data.frontDimension"
            (valueChange)="onFieldChange('frontDimension', $event)"
            placeholder="Ex: 195/60/R16"
            [required]="!!data.frontTireCount && data.frontTireCount !== '0'"
            [error]="errors.frontDimension"
          ></app-input-field>
          <app-input-field
            label="Indices"
            [value]="data.frontIndex"
            (valueChange)="onFieldChange('frontIndex', $event)"
            placeholder="Ex: 96H"
          ></app-input-field>
        </div>
        
        <app-input-field
          label="NB de pneus"
          [value]="data.frontTireCount"
          (valueChange)="onFieldChange('frontTireCount', $event)"
          placeholder="Nombre"
          type="number"
          [required]="true"
          [error]="errors.frontTireCount"
        ></app-input-field>
      </div>

      <!-- PNEU AR -->
      <div class="tire-section">
        <h3 class="section-title">
          <span>PNEU AR</span>
          <button 
            type="button"
            *ngIf="data.frontBrand || data.frontModel || data.frontDimension || data.frontIndex"
            (click)="copyAllFrontToRear()"
            class="copy-all-button"
            title="Copier toutes les données du pneu avant"
          >
            Copier tout
          </button>
        </h3>
        
        <div class="tire-type-row">
          <app-checkbox
            label="Été"
            [checked]="data.rear === 'summer'"
            (checkedChange)="onFieldChange('rear', $event ? 'summer' : '')"
          ></app-checkbox>
          <app-checkbox
            label="Toutes Saisons"
            [checked]="data.rear === 'allSeason'"
            (checkedChange)="onFieldChange('rear', $event ? 'allSeason' : '')"
          ></app-checkbox>
          <app-checkbox
            label="Hiver"
            [checked]="data.rear === 'winter'"
            (checkedChange)="onFieldChange('rear', $event ? 'winter' : '')"
          ></app-checkbox>
        </div>

        <div class="input-with-copy">
          <app-input-field
            label="Marque"
            [value]="data.rearBrand"
            (valueChange)="onFieldChange('rearBrand', $event)"
            placeholder="Michelin"
            [required]="!!data.rearTireCount && data.rearTireCount !== '0'"
            [error]="errors.rearBrand"
          ></app-input-field>
          <button 
            type="button"
            *ngIf="data.frontBrand"
            (click)="copyFrontBrandToRear()"
            class="copy-button"
            title="Copier la marque avant"
          >
            📋
          </button>
        </div>

        <div class="input-with-copy">
          <app-input-field
            label="Profil"
            [value]="data.rearModel"
            (valueChange)="onFieldChange('rearModel', $event)"
            placeholder="Primacy 5"
            [required]="!!data.rearTireCount && data.rearTireCount !== '0'"
            [error]="errors.rearModel"
          ></app-input-field>
          <button 
            type="button"
            *ngIf="data.frontModel"
            (click)="copyFrontModelToRear()"
            class="copy-button"
            title="Copier le profil avant"
          >
            📋
          </button>
        </div>

        <div class="dimension-row">
          <div class="input-with-copy">
            <app-input-field
              label="Dimension"
              [value]="data.rearDimension"
              (valueChange)="onFieldChange('rearDimension', $event)"
              placeholder="Ex: 195/60/R16"
              [required]="!!data.rearTireCount && data.rearTireCount !== '0'"
              [error]="errors.rearDimension"
            ></app-input-field>
            <button 
              type="button"
              *ngIf="data.frontDimension"
              (click)="copyFrontDimensionToRear()"
              class="copy-button"
              title="Copier la dimension avant"
            >
              📋
            </button>
          </div>
          <div class="input-with-copy">
            <app-input-field
              label="Indices"
              [value]="data.rearIndex"
              (valueChange)="onFieldChange('rearIndex', $event)"
              placeholder="Ex: 96H"
            ></app-input-field>
            <button 
              type="button"
              *ngIf="data.frontIndex"
              (click)="copyFrontIndexToRear()"
              class="copy-button"
              title="Copier les indices avant"
            >
              📋
            </button>
          </div>
        </div>

        <app-input-field
          label="NB de pneus"
          [value]="data.rearTireCount"
          (valueChange)="onFieldChange('rearTireCount', $event)"
          placeholder="Nombre"
          type="number"
          [required]="true"
          [error]="errors.rearTireCount"
        ></app-input-field>
      </div>
    </div>

    <!-- Forfaits et services -->
    <div class="collapsible-section">
      <button 
        class="section-header"
        (click)="toggleServices()"
        type="button"
      >
        <span>Forfaits et services</span>
        <span class="arrow">{{ showServices ? '▲' : '▼' }}</span>
      </button>
      
      <div *ngIf="showServices" class="section-content">
        <table class="services-table">
          <thead>
            <tr>
              <th>Service</th>
              <th>Quantité</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                Forfait MO <span class="required">*</span>
              </td>
              <td>
                <input 
                  type="number"
                  [value]="data.laborCount"
                  (input)="onFieldChange('laborCount', $any($event.target).value)"
                  placeholder="Nombre"
                  [class.error]="errors.laborCount"
                  class="service-input"
                />
                <div *ngIf="errors.laborCount" class="error-text">{{ errors.laborCount }}</div>
              </td>
            </tr>
            <tr>
              <td>
                Valve <span class="required">*</span>
              </td>
              <td>
                <input 
                  type="number"
                  [value]="data.valveCount"
                  (input)="onFieldChange('valveCount', $any($event.target).value)"
                  placeholder="Nombre"
                  [class.error]="errors.valveCount"
                  class="service-input"
                />
                <div *ngIf="errors.valveCount" class="error-text">{{ errors.valveCount }}</div>
              </td>
            </tr>
            <tr>
              <td>Azote</td>
              <td>
                <input 
                  type="number"
                  [value]="data.nitrogenCount"
                  (input)="onFieldChange('nitrogenCount', $any($event.target).value)"
                  placeholder="Nombre"
                  class="service-input"
                />
              </td>
            </tr>
            <tr>
              <td>Rép. crevaison</td>
              <td>
                <input 
                  type="number"
                  [value]="data.punctureRepairCount"
                  (input)="onFieldChange('punctureRepairCount', $any($event.target).value)"
                  placeholder="Nombre"
                  class="service-input"
                />
              </td>
            </tr>
            <tr>
              <td>Dépose / pose</td>
              <td>
                <input 
                  type="number"
                  [value]="data.mountingCount"
                  (input)="onFieldChange('mountingCount', $any($event.target).value)"
                  placeholder="Nombre"
                  class="service-input"
                />
              </td>
            </tr>
            <tr>
              <td>Permutation</td>
              <td>
                <input 
                  type="number"
                  [value]="data.rotationCount"
                  (input)="onFieldChange('rotationCount', $any($event.target).value)"
                  placeholder="Nombre"
                  class="service-input"
                />
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Options supplémentaires -->
    <div class="collapsible-section">
      <button 
        class="section-header"
        (click)="toggleOptions()"
        type="button"
      >
        <span>Options supplémentaires</span>
        <span class="arrow">{{ showOptions ? '▲' : '▼' }}</span>
      </button>
      
      <div *ngIf="showOptions" class="section-content">
        <div class="options-grid">
          <app-checkbox
            label="Assurance pneumatique"
            [checked]="data.tireInsurance"
            (checkedChange)="onFieldChange('tireInsurance', $event)"
          ></app-checkbox>
          <app-checkbox
            label="Assurance dépannage"
            [checked]="data.roadAssistance"
            (checkedChange)="onFieldChange('roadAssistance', $event)"
          ></app-checkbox>
          <app-checkbox
            label="Réutilisation valve élec."
            [checked]="data.valveReuse"
            (checkedChange)="onFieldChange('valveReuse', $event)"
          ></app-checkbox>
          <app-checkbox
            label="Entretien valves élect."
            [checked]="data.valveMaintenance"
            (checkedChange)="onFieldChange('valveMaintenance', $event)"
          ></app-checkbox>
          <app-checkbox
            label="Équilibrage type"
            [checked]="data.balancingType"
            (checkedChange)="onFieldChange('balancingType', $event)"
          ></app-checkbox>
          <app-checkbox
            label="Géométrie type"
            [checked]="data.geometryType"
            (checkedChange)="onFieldChange('geometryType', $event)"
          ></app-checkbox>
          <app-checkbox
            label="CONT. REG. AV-AR"
            [checked]="data.contReg"
            (checkedChange)="onFieldChange('contReg', $event)"
          ></app-checkbox>
        </div>
        
        <app-input-field
          label="Accord mise au déchet (nombre de pneus)"
          [value]="data.wasteAgreementCount"
          (valueChange)="onFieldChange('wasteAgreementCount', $event)"
          placeholder="Nombre de pneus"
          type="number"
        ></app-input-field>
      </div>
    </div>

    <div class="button-container">
      <app-button
        variant="secondary"
        (buttonClick)="onPrevious()"
      >
        Précédent
      </app-button>
      
      <app-button
        variant="primary"
        (buttonClick)="onNext()"
      >
        Suivant
      </app-button>
    </div>
  </div>
</div>

// proto/src/pages/TireSelection.tsx
import React, { useState } from 'react';
import { Button } from '../components/Button';
import { Checkbox } from '../components/Checkbox';
import { InputField } from '../components/InputField';
import { ChevronDownIcon, ChevronUpIcon, CopyIcon } from 'lucide-react';
interface TireData {
  front: string;
  rear: string;
  frontBrand: string;
  rearBrand: string;
  frontModel: string;
  rearModel: string;
  frontDimension: string;
  rearDimension: string;
  frontIndex: string;
  rearIndex: string;
  frontTireCount: string;
  rearTireCount: string;
  tireInsurance: boolean;
  roadAssistance: boolean;
  valveReuse: boolean;
  valveMaintenance: boolean;
  balancingType: boolean;
  geometryType: boolean;
  contReg: boolean;
  wasteAgreementCount: string;
  // Propriétés pour les forfaits
  laborCount: string;
  valveCount: string;
  nitrogenCount: string;
  punctureRepairCount: string;
  mountingCount: string;
  rotationCount: string;
}
interface TireSelectionProps {
  data: TireData;
  updateData: (data: Partial<TireData>) => void;
  onNext: () => void;
  onPrevious: () => void;
}
export const TireSelection = ({
  data,
  updateData,
  onNext,
  onPrevious
}: TireSelectionProps) => {
  // États pour contrôler l'affichage des sections dépliables
  const [showServices, setShowServices] = useState(false);
  const [showOptions, setShowOptions] = useState(false);
  const [errors, setErrors] = useState({
    frontBrand: '',
    rearBrand: '',
    frontModel: '',
    rearModel: '',
    frontDimension: '',
    rearDimension: '',
    frontTireCount: '',
    rearTireCount: '',
    laborCount: '',
    valveCount: ''
  });
  // Initialiser les données manquantes avec des valeurs par défaut
  const completeData = {
    front: data.front || '',
    rear: data.rear || '',
    frontBrand: data.frontBrand || '',
    rearBrand: data.rearBrand || '',
    frontModel: data.frontModel || '',
    rearModel: data.rearModel || '',
    frontDimension: data.frontDimension || '',
    rearDimension: data.rearDimension || '',
    frontIndex: data.frontIndex || '',
    rearIndex: data.rearIndex || '',
    frontTireCount: data.frontTireCount || '',
    rearTireCount: data.rearTireCount || '',
    tireInsurance: data.tireInsurance || false,
    roadAssistance: data.roadAssistance || false,
    valveReuse: data.valveReuse || false,
    valveMaintenance: data.valveMaintenance || false,
    balancingType: data.balancingType || false,
    geometryType: data.geometryType || false,
    contReg: data.contReg || false,
    wasteAgreementCount: data.wasteAgreementCount || '',
    // Initialisation des propriétés pour les forfaits
    laborCount: data.laborCount || '',
    valveCount: data.valveCount || '',
    nitrogenCount: data.nitrogenCount || '',
    punctureRepairCount: data.punctureRepairCount || '',
    mountingCount: data.mountingCount || '',
    rotationCount: data.rotationCount || ''
  };
  // Fonctions pour copier les données du pneu avant vers l'arrière
  const copyFrontBrandToRear = () => {
    updateData({
      rearBrand: completeData.frontBrand
    });
  };
  const copyFrontModelToRear = () => {
    updateData({
      rearModel: completeData.frontModel
    });
  };
  const copyFrontDimensionToRear = () => {
    updateData({
      rearDimension: completeData.frontDimension
    });
  };
  const copyFrontIndexToRear = () => {
    updateData({
      rearIndex: completeData.frontIndex
    });
  };
  // Fonction pour copier toutes les données du pneu avant vers l'arrière
  const copyAllFrontToRear = () => {
    updateData({
      rear: completeData.front,
      rearBrand: completeData.frontBrand,
      rearModel: completeData.frontModel,
      rearDimension: completeData.frontDimension,
      rearIndex: completeData.frontIndex,
      rearTireCount: completeData.frontTireCount
    });
  };
  // Validation des champs obligatoires
  const validate = () => {
    const newErrors = {
      frontBrand: '',
      rearBrand: '',
      frontModel: '',
      rearModel: '',
      frontDimension: '',
      rearDimension: '',
      frontTireCount: '',
      rearTireCount: '',
      laborCount: '',
      valveCount: ''
    };
    // Validation des pneus avant
    if (completeData.frontTireCount && completeData.frontTireCount !== '0') {
      if (!completeData.frontBrand) {
        newErrors.frontBrand = 'La marque est requise';
      }
      if (!completeData.frontModel) {
        newErrors.frontModel = 'Le profil est requis';
      }
      if (!completeData.frontDimension) {
        newErrors.frontDimension = 'La dimension est requise';
      }
    }
    // Validation des pneus arrière
    if (completeData.rearTireCount && completeData.rearTireCount !== '0') {
      if (!completeData.rearBrand) {
        newErrors.rearBrand = 'La marque est requise';
      }
      if (!completeData.rearModel) {
        newErrors.rearModel = 'Le profil est requis';
      }
      if (!completeData.rearDimension) {
        newErrors.rearDimension = 'La dimension est requise';
      }
    }
    // Validation du nombre de pneus
    if (!completeData.frontTireCount && !completeData.rearTireCount) {
      newErrors.frontTireCount = 'Le nombre de pneus est requis';
      newErrors.rearTireCount = 'Le nombre de pneus est requis';
    }
    // Validation des forfaits
    if (!completeData.laborCount) {
      newErrors.laborCount = 'Le forfait MO est requis';
    }
    if (!completeData.valveCount) {
      newErrors.valveCount = 'La valve est requise';
    }
    setErrors(newErrors);
    return !Object.values(newErrors).some(error => error);
  };
  const handleNext = () => {
    if (validate()) {
      onNext();
    }
  };
  return <div className="animate-fadeIn">
      <h2 className="text-2xl font-bold text-[#333333] mb-6">PNEUMATIQUES</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-4">
        {/* Colonne PNEU AV */}
        <div className="bg-blue-50 p-4 rounded-lg border border-blue-100">
          <h3 className="text-lg font-medium text-[#0054A4] mb-4">PNEU AV</h3>
          <div className="space-y-3">
            <div className="flex items-center space-x-4">
              <Checkbox label="Été" id="frontSummer" checked={completeData.front === 'summer'} onChange={() => updateData({
              front: 'summer'
            })} />
              <Checkbox label="Toutes Saisons" id="frontAllSeason" checked={completeData.front === 'allSeason'} onChange={() => updateData({
              front: 'allSeason'
            })} />
              <Checkbox label="Hiver" id="frontWinter" checked={completeData.front === 'winter'} onChange={() => updateData({
              front: 'winter'
            })} />
            </div>
            <InputField label="Marque" id="frontBrand" value={completeData.frontBrand} onChange={value => updateData({
            frontBrand: value
          })} placeholder="Michelin" required={!!completeData.frontTireCount && completeData.frontTireCount !== '0'} error={errors.frontBrand} />
            <InputField label="Profil" id="frontModel" value={completeData.frontModel} onChange={value => updateData({
            frontModel: value
          })} placeholder="Primacy 5" required={!!completeData.frontTireCount && completeData.frontTireCount !== '0'} error={errors.frontModel} />
            <div className="grid grid-cols-2 gap-3">
              <InputField label="Dimension" id="frontDimension" value={completeData.frontDimension} onChange={value => updateData({
              frontDimension: value
            })} placeholder="Ex: 195/60/R16" required={!!completeData.frontTireCount && completeData.frontTireCount !== '0'} error={errors.frontDimension} />
              <InputField label="Indices" id="frontIndex" value={completeData.frontIndex} onChange={value => updateData({
              frontIndex: value
            })} placeholder="Ex: 96H" />
            </div>
            <InputField label="NB de pneus" id="frontTireCount" value={completeData.frontTireCount} onChange={value => updateData({
            frontTireCount: value
          })} placeholder="Nombre" type="number" required error={errors.frontTireCount} />
          </div>
        </div>
        {/* Colonne PNEU AR */}
        <div className="bg-blue-50 p-4 rounded-lg border border-blue-100">
          <h3 className="text-lg font-medium text-[#0054A4] mb-4 flex justify-between items-center">
            <span>PNEU AR</span>
            {(completeData.frontBrand || completeData.frontModel || completeData.frontDimension || completeData.frontIndex) && <button type="button" onClick={copyAllFrontToRear} className="text-xs bg-blue-100 hover:bg-blue-200 text-[#0054A4] px-2 py-1 rounded-md flex items-center" title="Copier toutes les données du pneu avant">
                <CopyIcon className="h-3 w-3 mr-1" /> Copier tout
              </button>}
          </h3>
          <div className="space-y-3">
            <div className="flex items-center space-x-4">
              <Checkbox label="Été" id="rearSummer" checked={completeData.rear === 'summer'} onChange={() => updateData({
              rear: 'summer'
            })} />
              <Checkbox label="Toutes Saisons" id="rearAllSeason" checked={completeData.rear === 'allSeason'} onChange={() => updateData({
              rear: 'allSeason'
            })} />
              <Checkbox label="Hiver" id="rearWinter" checked={completeData.rear === 'winter'} onChange={() => updateData({
              rear: 'winter'
            })} />
            </div>
            <div className="relative">
              <InputField label="Marque" id="rearBrand" value={completeData.rearBrand} onChange={value => updateData({
              rearBrand: value
            })} placeholder="Michelin" required={!!completeData.rearTireCount && completeData.rearTireCount !== '0'} error={errors.rearBrand} />
              {completeData.frontBrand && <button type="button" onClick={copyFrontBrandToRear} className="absolute right-2 top-9 text-[#0054A4] hover:text-blue-700 p-1 rounded-md bg-blue-50 hover:bg-blue-100 transition-colors" title="Copier la marque avant">
                  <CopyIcon className="h-4 w-4" />
                </button>}
            </div>
            <div className="relative">
              <InputField label="Profil" id="rearModel" value={completeData.rearModel} onChange={value => updateData({
              rearModel: value
            })} placeholder="Primacy 5" required={!!completeData.rearTireCount && completeData.rearTireCount !== '0'} error={errors.rearModel} />
              {completeData.frontModel && <button type="button" onClick={copyFrontModelToRear} className="absolute right-2 top-9 text-[#0054A4] hover:text-blue-700 p-1 rounded-md bg-blue-50 hover:bg-blue-100 transition-colors" title="Copier le profil avant">
                  <CopyIcon className="h-4 w-4" />
                </button>}
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="relative">
                <InputField label="Dimension" id="rearDimension" value={completeData.rearDimension} onChange={value => updateData({
                rearDimension: value
              })} placeholder="Ex: 195/60/R16" required={!!completeData.rearTireCount && completeData.rearTireCount !== '0'} error={errors.rearDimension} />
                {completeData.frontDimension && <button type="button" onClick={copyFrontDimensionToRear} className="absolute right-2 top-9 text-[#0054A4] hover:text-blue-700 p-1 rounded-md bg-blue-50 hover:bg-blue-100 transition-colors" title="Copier la dimension avant">
                    <CopyIcon className="h-4 w-4" />
                  </button>}
              </div>
              <div className="relative">
                <InputField label="Indices" id="rearIndex" value={completeData.rearIndex} onChange={value => updateData({
                rearIndex: value
              })} placeholder="Ex: 96H" />
                {completeData.frontIndex && <button type="button" onClick={copyFrontIndexToRear} className="absolute right-2 top-9 text-[#0054A4] hover:text-blue-700 p-1 rounded-md bg-blue-50 hover:bg-blue-100 transition-colors" title="Copier les indices avant">
                    <CopyIcon className="h-4 w-4" />
                  </button>}
              </div>
            </div>
            <InputField label="NB de pneus" id="rearTireCount" value={completeData.rearTireCount} onChange={value => updateData({
            rearTireCount: value
          })} placeholder="Nombre" type="number" required error={errors.rearTireCount} />
          </div>
        </div>
      </div>
      {/* Tableau des forfaits - Section cliquable */}
      <div className="bg-gray-50 p-4 rounded-lg border mb-6">
        <button className="flex justify-between items-center w-full text-left" onClick={() => setShowServices(!showServices)}>
          <h3 className="text-lg font-medium text-gray-700">
            Forfaits et services
          </h3>
          {showServices ? <ChevronUpIcon className="h-5 w-5 text-gray-500" /> : <ChevronDownIcon className="h-5 w-5 text-gray-500" />}
        </button>
        {showServices && <div className="mt-4 overflow-x-auto">
            <table className="w-full border-collapse">
              <thead>
                <tr className="bg-blue-50">
                  <th className="border border-gray-300 px-4 py-2 text-left">
                    Service
                  </th>
                  <th className="border border-gray-300 px-4 py-2 text-left">
                    Quantité
                  </th>
                </tr>
              </thead>
              <tbody>
                {/* Forfait main d'œuvre */}
                <tr>
                  <td className="border border-gray-300 px-4 py-2 font-medium">
                    Forfait MO <span className="text-red-500">*</span>
                  </td>
                  <td className="border border-gray-300 px-4 py-2">
                    <input type="number" className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4] ${errors.laborCount ? 'border-red-500' : 'border-gray-300'}`} value={completeData.laborCount} onChange={e => updateData({
                  laborCount: e.target.value
                })} placeholder="Nombre" />
                    {errors.laborCount && <p className="mt-1 text-xs text-red-500">
                        {errors.laborCount}
                      </p>}
                  </td>
                </tr>
                {/* Valves */}
                <tr>
                  <td className="border border-gray-300 px-4 py-2 font-medium">
                    Valve <span className="text-red-500">*</span>
                  </td>
                  <td className="border border-gray-300 px-4 py-2">
                    <input type="number" className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4] ${errors.valveCount ? 'border-red-500' : 'border-gray-300'}`} value={completeData.valveCount} onChange={e => updateData({
                  valveCount: e.target.value
                })} placeholder="Nombre" />
                    {errors.valveCount && <p className="mt-1 text-xs text-red-500">
                        {errors.valveCount}
                      </p>}
                  </td>
                </tr>
                {/* Azote */}
                <tr>
                  <td className="border border-gray-300 px-4 py-2 font-medium">
                    Azote
                  </td>
                  <td className="border border-gray-300 px-4 py-2">
                    <input type="number" className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4]" value={completeData.nitrogenCount} onChange={e => updateData({
                  nitrogenCount: e.target.value
                })} placeholder="Nombre" />
                  </td>
                </tr>
                {/* Réparation crevaison */}
                <tr>
                  <td className="border border-gray-300 px-4 py-2 font-medium">
                    Rép. crevaison
                  </td>
                  <td className="border border-gray-300 px-4 py-2">
                    <input type="number" className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4]" value={completeData.punctureRepairCount} onChange={e => updateData({
                  punctureRepairCount: e.target.value
                })} placeholder="Nombre" />
                  </td>
                </tr>
                {/* Dépose/pose */}
                <tr>
                  <td className="border border-gray-300 px-4 py-2 font-medium">
                    Dépose / pose
                  </td>
                  <td className="border border-gray-300 px-4 py-2">
                    <input type="number" className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4]" value={completeData.mountingCount} onChange={e => updateData({
                  mountingCount: e.target.value
                })} placeholder="Nombre" />
                  </td>
                </tr>
                {/* Permutation */}
                <tr>
                  <td className="border border-gray-300 px-4 py-2 font-medium">
                    Permutation
                  </td>
                  <td className="border border-gray-300 px-4 py-2">
                    <input type="number" className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-1 focus:ring-[#0054A4]" value={completeData.rotationCount} onChange={e => updateData({
                  rotationCount: e.target.value
                })} placeholder="Nombre" />
                  </td>
                </tr>
              </tbody>
            </table>
          </div>}
      </div>
      {/* Options supplémentaires - Section cliquable */}
      <div className="bg-gray-50 p-4 rounded-lg border mb-6">
        <button className="flex justify-between items-center w-full text-left" onClick={() => setShowOptions(!showOptions)}>
          <h3 className="text-lg font-medium text-gray-700">
            Options supplémentaires
          </h3>
          {showOptions ? <ChevronUpIcon className="h-5 w-5 text-gray-500" /> : <ChevronDownIcon className="h-5 w-5 text-gray-500" />}
        </button>
        {showOptions && <div className="mt-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
              <Checkbox label="Assurance pneumatique" id="tireInsurance" checked={completeData.tireInsurance} onChange={checked => updateData({
            tireInsurance: checked
          })} />
              <Checkbox label="Assurance dépannage" id="roadAssistance" checked={completeData.roadAssistance} onChange={checked => updateData({
            roadAssistance: checked
          })} />
              <Checkbox label="Réutilisation valve élec." id="valveReuse" checked={completeData.valveReuse} onChange={checked => updateData({
            valveReuse: checked
          })} />
              <Checkbox label="Entretien valves élect." id="valveMaintenance" checked={completeData.valveMaintenance} onChange={checked => updateData({
            valveMaintenance: checked
          })} />
              <Checkbox label="Équilibrage type" id="balancingType" checked={completeData.balancingType} onChange={checked => updateData({
            balancingType: checked
          })} />
              <Checkbox label="Géométrie type" id="geometryType" checked={completeData.geometryType} onChange={checked => updateData({
            geometryType: checked
          })} />
              <Checkbox label="CONT. REG. AV-AR" id="contReg" checked={completeData.contReg} onChange={checked => updateData({
            contReg: checked
          })} />
            </div>
            {/* Nouveau champ pour Accord mise au déchet */}
            <div className="mt-4">
              <InputField label="Accord mise au déchet (nombre de pneus)" id="wasteAgreementCount" value={completeData.wasteAgreementCount} onChange={value => updateData({
            wasteAgreementCount: value
          })} placeholder="Nombre de pneus" type="number" />
            </div>
          </div>}
      </div>
      <div className="mt-8 flex justify-between">
        <Button onClick={onPrevious} variant="secondary">
          Précédent
        </Button>
        <Button onClick={handleNext}>Suivant</Button>
      </div>
    </div>;
};
